Amsterdam/signals

api/src/signals/django_signals.py
api/src/signals/messaging/send_emails.py
api/src/signals/settings.py
api/src/signals/tasks.py
api/src/signals/tests/factories.py
api/src/signals/tests/test_django_signals.py
api/src/signals/tests/test_post_api.py
api/src/signals/tests/test_tasks.py

- Implemented `send_mail_apptimize` task
- Updated `SignalFactory` to let it work out-of-the-box
- Apptimize mail is send on create/update of the object (on model `save`)

SIG-368 send mail Apptimize on category changed

---

api/src/signals/settings.py
api/src/signals/tests/utils/test_datawarehouse.py
api/src/signals/utils/datawarehouse.py

- Celery beat scheduling task `task_save_csv_files_datawarehouse` every night at 4am
- Cleanup previous files on storage backend
- Added state db value to CSV dump for `statuses.csv`

Sig 393 celery beat CSV dumps

---

api/requirements.txt

Trivial fix for warning during docker build (supposed version incompatibility).

Bump version of Datapunt authorization_django

---

api/app/signals/__init__.py

* Overall version 0.6.2
* V0 API version 0.1.1
* V1 API version 1.1.0 (unchanged)

Version bump to 0.6.2. Added created_by where neccessary.

---

api/app/signals/__init__.py

Updated APIs with HEROPENEN status (affects both V0 and V1) - all backwards compatible. Hence three version bumps.

Version bump to SIA 0.8.0

---

api/app/signals/apps/signals/migrations/0095_SIG-1708_part-1.py
api/app/tests/apps/api/v1/test_private_category_endpoint.py

PART 1 of the SIG-1708 New categories
In overleg met Arvid is besloten om dit in 2 delen op te pakken. Er worden 5 nieuwe categorieen toegevoegd en hiervoor
zal de bulk actie voor hercategorisering plaatsvinden.
Het eerste deel bevat de volgende categorieën:
- Drijfvuil bevaarbaar water
- Uitwerpselen
- Gladheid winterdienst
- Graffiti / wildplak
- Brug

SIG-1708 Part 1 (Part 2 is now SIG-2242)

---

api/app/signals/apps/api/v1/serializers/departments.py
api/app/tests/apps/api/v1/test_private_departments.py

SIG-2287 [BE] Afdeling geeft categorie zonder main slug terug
Fixed when rendering the URL for a parent category use the correct `serializer_url_field`

SIG-2287 fix when rendering the URL for a parent category

---

api/app/signals/settings/base.py

Currently we are unable to reuse the application, as we are not able to set the ALLOWED_HOSTS variable. This change allows configuring ALLOWED_HOSTS through an environment variable.
Multiple hosts can be configured by separating the hosts with a comma, e.g.:
```
ALLOWED_HOSTS=api.data.amsterdam.nl,acc.api.data.amsterdam.nl
```

Make ALLOWED_HOSTS configurable through environment variables

---

.github/workflows/ci.yml
api/app/tox.ini

This PR introduces continuous integration using GitHub Actions. This allows pull requests from external contributors to be tested securely.
- The [GitHub Actions](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions) manual served as template of this setup.
- Pip modules are cached between builds.
- Code coverage report is generated in HTML and uploaded using [artifacts](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts).
This setup is easily extendible for testing against multiple Python versions with the [build matrix feature](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).
We could optimize this setup further by caching the …

Run tests using GitHub Actions

---

api/app/signals/apps/api/v1/views/signal.py
api/app/tests/apps/api/v1/test_public_signal_endpoint.py

V1 public signals list endpoint should return a 404 instead of a 500

V1 public signals list endpoint should return a 404 instead of a 500

---

api/Dockerfile

Updated Dockerfile to use amsterdam/python:3.8.2-buster

Updated Dockerfile to use amsterdam/python:3.8.2-buster

---

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/api/v1/serializers/area.py
api/app/tests/apps/api/v1/json_schema/get_signals_v1_private_areas.json
api/app/tests/apps/api/v1/json_schema/get_signals_v1_public_areas.json

The `geometry` field in the areas endpoint response results in a very large dataset. Therefore it is removed. If this data is needed to draw shapes the `/signals/v1/public/areas/geography` or /signals/v1/private/areas/geography` endpoints will provide the geosjon to do so.

Removed geometry from areas endpoint response

---

api/app/signals/apps/search/config.py
api/app/signals/apps/search/settings.py
api/app/signals/settings/base.py
docker-compose.yml

This MR makes the Elasticsearch settings configurable by environment variables.
Fixes https://github.com/Signalen/backend/issues/36.

Make Elasticsearch settings configurable

---

api/app/signals/settings/base.py

This makes the JWKS_URL setting configurable through an environment variable.
Fixes https://github.com/Signalen/backend/issues/41

Make JWKS url configurable

---

api/app/signals/urls.py

Without this **Cross Site Request Forgery** exempt it is not possible to
use a remote GraphQL client

(Fix) Exempt GraphQL view from the CSRF view protection

---

api/app/signals/apps/signals/admin.py

Enable basic (add/edit) category maintenance.
Delete is disabled, should be done by is_active flag.
Enabled main cat filter

Basic Django admin category edit capabilities

---

api/app/signals/apps/api/v1/validation/address/pdok.py
api/app/signals/settings/base.py

Currently the PDOKAddressValidation.py has hardcoded municipalities values:
```
MUNICIPALITIES = (
'Amsterdam',
'Amstelveen',
'Weesp',
)
```
We need make this configurable for other municipalities

make pdok municipalities configurable

---

Jenkinsfile

This reverts commit 6972ceb0edd5e072f7a87743c2f3ba938a44c46a.
This commit re-enabled the CMDB deployment for signals backend. CMDB deployment is planned for Friday morning (24-07).

Re-enable CMDB deployment

---

api/Dockerfile

Celery beat writes `/app/celerybeat.pid` file. Allow this file to be written from user 'datapunt', so that we don't need to start the container as user 'root' for celery beat to work.

Allow user datapunt to create files in /app

---

api/app/signals/settings/base.py
api/app/signals/settings/development.py

This allows developers to configure their own setup and support for example running Dex locally.

Allow configuration of SIGNALS_AUTHZ in development using environment variables

---

api/app/signals/apps/dataset/management/commands/load_categories.py
api/app/tests/apps/dataset/management/commands/test_load_categories.py

When loading categories, we cannot assume that a slug name is unique. It's only unique in combination with its parent. The importer did not take existing 'duplicates' into account when importing.
This PR fixes handling of the slug name. A unit test is added to illustrate the issue.

Fixed handling of 'duplicate' slug names

---

api/app/signals/apps/api/v0/views.py

Currently the retrieve of 'overig-overig' sub cat fails when we  have multiple 'overig' under different main category. This small bugfix ensures that the parent slug name should be 'overig' when retrieving 'overig-overig'

when retrieving 'overig-overig' also check the parent slug

---

api/app/signals/apps/api/ml_tool/utils.py
api/app/signals/apps/api/v1/filters/question.py

fixed 2 issues with on-unique main / sub slug combination
1. get_category_from_prediction() does not handle 'duplicate' subcat (but with different parent) correctly 
2. QuestionFilterSet should filter on active categories only

bugfix: 'duplicate' subcat with different parent handling

---

api/app/signals/apps/api/v1/validation/address/pdok.py

BE fix for https://github.com/Signalen/backend/issues/73
see FE PR https://github.com/Amsterdam/signals-frontend/pull/1216 for more details
Pdok uses Solr. Any of these should work:
```
gemeentenaam:("den bosch" "boxtel" "altena")
gemeentenaam:("den bosch" OR "boxtel" OR "altena")
gemeentenaam:"den bosch" gemeentenaam:"boxtel" gemeentenaam:"altena"
gemeentenaam:"den bosch" OR gemeentenaam:"boxtel" OR gemeentenaam:"altena"
```
more info: https://stackoverflow.com/questions/14595767/how-to-select-multiple-values-in-solr-via-the-query-string

fix how list of "gemeentenaam" is handled in pdok suggest query

---

api/app/signals/apps/signals/admin.py

Currently the django admin uses a 'default' leaflet to display the area polygons. These maps/layers are outdated for the Netherlands. This PR uses open street map component in the django admin.

Use OSM leaflet in Django Admin

---

api/app/signals/apps/signals/models/history.py

There's a hardcoded SIA string in the history view. 
Fixes issue https://github.com/Signalen/backend/issues/71

rename 'SIA systeem' to 'Signalen systeem' in history view

---

.github/workflows/ci.yml

As ubuntu-latest will [soon be replaced](https://github.com/actions/virtual-environments/issues/1816).

Pin Github actions on Ubuntu 18.04

---

api/app/signals/apps/api/v1/serializers/expression.py
api/app/signals/apps/services/domain/dsl.py
api/app/signals/apps/signals/managers.py
api/app/signals/apps/signals/models/routing_expression.py

- modelmanager was assigned to `.actions` instead of `.objects` for RoutingExpression model.
- when updating routing, the directing department relation was used
- make extra questions answers available for dsl. For now we expose extra property id and its value to the context. This is only being done if the id of the extra property is not available as signal attribute (we avoid attributes being overwritten this way)

fixed 2 issues regarding routing

---

api/app/signals/apps/signals/migrations/0129_new_subcategory_kerstbomen.py

Migration of 0129 fails when parent category does not exists

only apply new category if parent is present (main category 'afval' is not always present in other municipalities)

---

api/app/signals/apps/services/domain/dsl.py
api/app/signals/apps/signals/admin.py
api/app/tests/apps/signals/test_routing_mechanism.py

During testing two issues were discovered
- Since we don't have validation in place for the routing (currently done via django admin) compilation errors can occur during evaluation of rules. Exceptions will stop evaluation of other rules
- Runtime exceptions (such as 1/0) should also not stop evaluation of other rules
This PR corrects this behavior by doing the following:
- compilation errors will set rule to in_active and continue flow
- runtime errors will be handled and will not prevent other rules from being executed
Add compilation check to modeladmin(routingexpression). If expression contains syntax errors, rule will be deactivated and user will get a notice. We should do full validation (check for valid identifiers in contex) after this commit. It requires refactor of the …

add graceful handling of compile and runtime exceptions

---

api/app/signals/apps/api/v1/filters/signal.py
api/app/tests/apps/api/v1/test_filters.py

Fixed the 'has_changed_children' filter. 
When True is given at least ONE OF the children must have an update_at after the parents updated_at. 
When False is given ALL children's updated_at must be before the parents updated_at.

Changed the 'has_changed_children' filter to work correctly

---

api/app/signals/settings/base.py

Currently the KTO settings are hardcoded. We should read them from the environment. Only one FEEDBACK_ENV_FE_MAPPING setting is expected per container.

read FEEDBACK_ENV_FE_MAPPING from env

---

api/app/signals/apps/reporting/csv/utils.py
api/app/tests/apps/reporting/test_datawarehouse.py

Currently the generated csv zip filename does not include the date in the filename. It's was requested to have the date stamp in the file name.

Also include date in csv-zip-dump filename

---

api/app/signals/apps/email_integrations/reporter/mail_actions.py
api/app/tests/apps/email_integrations/reporter/test_email_templates.py

The e-mail template functionality did not correctly render variables with special characters when rendering the e-mail title and Markdown.
For example when `ORGANIZATION_NAME` was set to `'s-Hertogenbosch`:
- The Django auto-escaping function would render the e-mail template `{{ ORGANIZATION_NAME}}` to Markdown with `&#39;s-Hertogenbosch`.
- The Markdown renderer did not touch the HTML-escaped characters and performed HTML-escaping again. 
The resulting e-mail contained: `&#39;s-Hertogenbosch`
This PR fixes this:
- Double escaping is not performed any more. Escaping HTML is now handled once by the Markdown parser.
- E-mail titles are not escaped any more.
Closes Signalen/backend#96

Do not escape e-mail title and variables that are used for rendering Markdown

---

api/app/tests/apps/api/v1/test_private_signal_endpoint.py

Added unit test to proof that it is possible to see history of a Signal without the correct permissions, this needs to be fixed

Added unit test to proof that it is possible to see history of a Signal without the correct permissions, this needs to be fixed

---

api/app/signals/apps/api/v1/views/signal.py
api/app/tests/apps/api/v1/test_history_endpoint.py
api/app/tests/apps/api/v1/test_private_signal_endpoint.py

Fixed bug in history that made it possible to view history of Signals that a user cannot access

fix bug in history endpoint

---

README.md
docs/CONTRIBUTING.md

Co-authored-by: Felix Faassen <felix@publiccode.net>
Add text to README and CONTRIBUTING to mention the roles of the Product
and Technical Steering groups and the Foundation.
https://github.com/Signalen/backend/issues/108
(Not applicable)

Add stewardship incubation text

---

utils/get_signals.py

The util scripts now use keycloak to get the access_token, also used as an example for external parties

Utils GetAccessToken now uses Keycloak

---

api/app/signals/settings/base.py
api/app/signals/settings/development.py

The application currently implicitly trusts an insecure testing key when the `PUB_JWKS` setting is not set. This could easily lead to insecure behavior when system administrators forget to set `PUB_JWKS`.
This PR fixes this implicit behavior and only loads the JWKS testing key during development and testing.

Make JWKS setting secure by default

---

api/app/signals/apps/api/v1/views/pdf.py
api/app/signals/apps/signals/factories/__init__.py
api/app/signals/apps/signals/factories/attachment.py
api/app/signals/settings/base.py
api/app/tests/apps/api/v1/test_pdf.py

This, currently draft, PR changes the PDF rendering to work around a GDK-pixbuf bug that renders some JPGs unusable. We pass images through PIL and resize (if they are large), base64 encode them and include them in the PDF. The attachments are now accessed through the `default_storage`.

SIG-3499 resize and base64 encode images in PDF

---

api/app/signals/apps/api/v1/serializers/attachment.py
api/app/signals/settings/base.py

Introduce `API_MAX_UPLOAD_SIZE` in project settings and allow it to be overridden through an environment variable.

SIG-2680 Expose setting for maximum allowed size for an attachment

---

api/app/signals/apps/reporting/csv/datawarehouse/locations.py

When exporting csv for dwh, and stadsdelen is used via 'district' configuration: the stadsdeel field remains empty during export. We should fallback on the configured area_code in this case

Use area_code fallback when stadsdeel is unknown during csv export

---

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/users/factories.py
api/app/signals/apps/users/v1/filters.py
api/app/tests/apps/users/v1/test_filters.py

This adds a feature to the backend to filter the user list on department code and name. This is used by the frontend to show show a list of users that a Signal is assigned to.
Closes Signalen/backend#113

Add ability to filter user list on department code

---

api/app/signals/apps/api/templates/api/pdf/print_signal.html
api/app/signals/apps/api/v1/views/pdf.py
api/app/signals/apps/services/domain/images.py
api/app/signals/apps/sigmax/stuf_protocol/outgoing/pdf.py
api/app/tests/apps/api/v1/test_pdf.py
api/app/tests/apps/services/domain/images.py
api/app/tests/apps/services/images.py

Work in progress refactor of PDF generating and image handling code. Messages to Sigmax and downloaded PDFs will use the same underlying rendering (moved to the services app).

SIG-3510 add image filetype check to Sigmax PDF rendering

---

api/app/signals/apps/dataset/sources/gebieden.py

Reimporting stadsdeel, wijk or buurt data resulted in a database constraint being violated, that is now fixed. Behavior matches the other geo datasets that SIA uses.

SIG-3605 reimport of stadsdeel (wijk or buurt) data no longer fails

---

api/requirements.txt
api/requirements/req-base.txt
docs/topics/application-design.md

This PR adds the [ddtrace](https://ddtrace.readthedocs.io/en/stable/) package that enables us to use [DataDog Tracing](https://docs.datadoghq.com/tracing/python/). The package can be enabled by overriding the startup command of the container:
```bash
ddtrace-run uwsgi ...
```
Closes Signalen/backend#122

Add DataDog Tracing package

---

api/app/signals/apps/dataset/sources/cbs.py
api/app/signals/apps/dataset/sources/shape.py

When loading areas via manage.py load_areas, a get_or_create is used with all properties. When for example a description was changed, this would cause an error during import. We should get_or_create on code field only and supply the rest as defaults.

load_areas: check existing type using code only

---

api/app/signals/apps/api/v1/serializers/__init__.py
api/app/signals/apps/api/v1/serializers/empty.py
api/app/signals/apps/api/v1/views/signal.py

1) The public map endpoint bypasses DRF for serialization. But we are using bits of it. When accessing the endpoint via a browser an assertion error is shown. In order to solve this, an empty serializer has been added.
2) It's also undesirable to include the status VERZOEK_TOT_HEROPENEN and GEANNULEERD on the map
This PR addresses both issues

fixes assertion error on public map endpoint and filter out undesired status

---

api/app/signals/apps/reporting/csv/datawarehouse/__init__.py
api/app/signals/apps/reporting/csv/datawarehouse/signals.py
api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
api/app/signals/apps/reporting/management/commands/dumpcsv.py
api/app/tests/apps/reporting/management/commands/test_command.py

We need to dump the assigned user in the csv. It can be solved by:
1. add additional field at normal signals.csv
2. add additional file containing [signal_id, email]
Since the dump code is executed in celery and no setting is available for assigned_user (it always works in the back-end, but can be configured in the front-end), we cannot conditionally enable this dump (unless we introduce an additional setting in the celery env)
Solution 1 is probably might break consumers of the 'standard' signals.csv.
I choose solution 2 to create a separate file. Would this work?

Proposal for additional signal-assigned user relation csv

---

api/app/signals/apps/api/generics/permissions.py
api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/api/v1/urls.py
api/app/signals/apps/users/v1/filters.py
api/app/signals/apps/users/v1/serializers/__init__.py
api/app/signals/apps/users/v1/serializers/user.py
api/app/signals/apps/users/v1/views/__init__.py
api/app/signals/apps/users/v1/views/user.py
api/app/tests/apps/users/v1/test_users.py

The "view_user" and "sia_read" permissions are now mandatory to view users + refactored the "v1/private/me" endpoint to be in its own view + added tests

The "view_user" permission is now mandatory to view information on the "/v1/private/users/" endpoint

---

api/app/signals/apps/signals/models/attachment.py
api/app/tests/apps/api/v1/test_public_signal_endpoint.py
api/app/tests/apps/signals/test_models.py

SIG-3610 Clean-up Attachment model, removed unused resize code

SIG-3610 Clean-up Attachment model, removed unused resize code

---

docs/README.md
docs/topics/dependencies.md
docs/topics/signalen-and-standard-for-public-code.md

Initial documentation of dependency maturity. Most are mature or indirect dependencies of Django which is mature.
See: https://github.com/Signalen/backend/issues/123
(removed checklist items which do not apply to documentation)

Document dependency maturity (issue #123)

---

api/app/signals/apps/signals/management/commands/calculate_deadlines.py
api/app/tests/apps/signals/management/commands/test_calculate_deadlines.py

The deadlines for handling complaints are only calculated upon a new category assignment. This means that the SIA Amsterdam dataset contains many complaints that have no deadlines (and are still open). This PR adds a management command to calculate deadlines for any open signals/complaints that have no deadline.

SIG-3642 Calculate deadlines for open signals/complaints that have none.

---

api/app/signals/apps/reporting/csv/datawarehouse/__init__.py
api/app/signals/apps/reporting/csv/datawarehouse/signals.py
api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
api/app/signals/apps/reporting/management/commands/dumpcsv.py
api/app/tests/apps/reporting/management/commands/test_command.py

Similar to directing departments, we need an export of the routing department relation.
It's a copy of the directing_department export except for the relation type. 
A separate file was chosen to avoid format changes.

add export of routing department relation

---

api/app/signals/apps/api/v1/serializers/attachment.py
api/app/tests/apps/api/v1/test_private_signal_endpoint.py
api/app/tests/apps/api/v1/test_public_signal_endpoint.py

This PR adds validation of file extensions for uploaded attachments. We accept .gif, .jpg, .jpeg and .png.
- The code contains some traces of handling non-image attachment uploads. What do we do with them? I suggest to keep them in as we are going to work on this in Signalen/backend#54.

Validate file extension of uploaded attachments, only accept image extensions

---

api/app/signals/__init__.py
api/requirements.txt

Maintenance, update Django to version 2.2.20. Bump internal SIA version to 0.21.3.

Chore update Django to version 2.2.20

---

api/app/signals/apps/dataset/management/commands/load_categories.py
api/app/tests/apps/dataset/management/commands/json_data/categories-update.json
api/app/tests/apps/dataset/management/commands/test_load_categories.py

Category.slug field is defined as: `slug = AutoSlugField(populate_from=['name', ], blank=False, overwrite=False, editable=False)`
The load_categories command tries to load the slug directly. The slug field is generally ignored, and the description (`Name`) field is used. We should therefore supply slugified `Name` as slug. Also prevent updating the `slug` field, since this is not permitted (even if its the same value)

Load_categories incorrectly determines slug while importing

---

docs/topics/signalen-and-standard-for-public-code.md

Updated the Standard for Public Code so that it reflects the actual reuse by 's-Hertogenbosch. Fixes #773
Can we get verified that `any secret, undisclosed, proprietary or non-open licensed code or services for execution and understanding.` was not a problem for the implementation? Perhaps @CBuiVNG can weigh in on that?

Update checklist that Signalen is reused by more parties

---

api/app/signals/apps/api/filters/signal.py
api/app/signals/apps/api/filters/utils.py
api/app/tests/apps/api/test_filters.py

The area code filter is defined as a multiple choice filter. The lookup choice list was missing the 'null' value which makes it impossible to filter for 'not-assigned'

Allow null value in choice area_code filter

---

api/app/signals/apps/api/serializers/category.py
api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/signals/migrations/0140_category_note.py
api/app/signals/apps/signals/models/category.py
api/app/tests/apps/api/test_private_category_endpoint.py

Add a note field to category model, expose it in API. Note this field's history is not tracked.

SIG-3662 Add note field to category, expose it in API.

---

api/app/signals/apps/services/domain/auto_create_children.py
api/app/tests/apps/services/domain/test_auto_create_children.py

The feature that creates child signals automatically for complaints about garbage containers needs more triggering categories. Specifically the broken container categories should also trigger child signal creation. Note that all child signals are created in the full container categories[1].
[1] We cannot differentiate between a broken or a full paper container in a complaint classified as full paper container. The map select functionality for containers does not provide enough information to make the distinction. Business made the decision to classify these automatically created child signals as complaints about full containers.

SIG-3761 add additional trigger categories to automatic child creation

---

api/app/signals/apps/services/domain/auto_create_children.py
api/app/tests/apps/services/domain/test_auto_create_children.py

Attachments are now copied to the automatically created children

Attachments are now copied to the automatically created children

---

api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
api/app/signals/apps/reporting/csv/utils.py
api/app/tests/apps/reporting/test_datawarehouse.py

We would to rotate the amount of zip files when generating them for the csv end point.
The default is set to 30 files, and can be overridden by a setting in django admin (celery task)

Added support for dataware house zip file rotation

---

api/app/signals/apps/feedback/utils.py
api/app/signals/settings/base.py
api/app/signals/settings/development.py
api/app/signals/settings/testing.py
api/app/tests/apps/email_integrations/test_mail.py
api/app/tests/apps/feedback/test_feedback.py

Added a setting to contain the frontend url, FE_URL. This setting replaces the FEEDBACK_ENV_FE_MAPPING setting currently available. The feedback util function get_fe_application_location will return the FE_URL and if it is not set it will fallback on the FEEDBACK_ENV_FE_MAPPING. This will be refactored in the near future

Added FRONTEND_URL setting in favour of the FEEDBACK_ENV_FE_MAPPING

---

api/app/signals/apps/reporting/rest_framework/serializers.py
api/app/signals/apps/reporting/tests/rest_framework/test_views.py

Reporting endpoint now returns department code instead of department name + added this to the unit tests

Reporting endpoint returns department code instead of name

---

docker-compose.yml

Feedback functionality does not work "out of the box" on development due to missing environment configuration.
Closes Signalen/backend#141

Make sure feedback functionality works on development as well

---

api/requirements.txt
api/requirements/req-base.txt
docs/topics/application-design.md

We now monitor endpoints using [Linkerd](https://linkerd.io/) and we collect container logs with [Promtail](https://grafana.com/docs/loki/latest/clients/promtail/).

Remove DataDog Tracing package as it is not being used any more

---

api/app/signals/apps/services/domain/dsl.py
api/app/tests/apps/dsl/test_dsl.py

We need to make a distinction between days when routing a signal. Signals in the weekend can be routed differently compared to weekdays. For this purpose a variable 'day' is introduced similar to 'time'

add day variable to dsl context

---

api/app/signals/apps/questionnaires/migrations/0004_alter_questiongraph_name.py

Add missing migration from PR 839, that is QuestionGraph.name became non-unique and nullable. That was not reflected by the migrations. This PR fixes that.

Chore add missing migration for QuestionGraph.name

---

api/app/signals/apps/search/documents/signal.py
api/app/signals/apps/search/settings.py
api/app/signals/settings/base.py

This PR fixes a bug that the Elasticsearch index is not configurable. It always defaulted to `sia_signals`. 
⚠️  This change is breaking for deployments that currently configure `ELASTICSEARCH_INDEX` to something else then `signals`.
Closes https://github.com/Signalen/backend/issues/161

Fix Elasticsearch index setting that is not working

---

api/app/signals/apps/questionnaires/rest_framework/views/public.py
api/app/signals/apps/questionnaires/services/questionnaires.py
api/app/signals/apps/questionnaires/tests/rest_framework/views/test_public_sessions_endpoint.py
api/app/signals/apps/questionnaires/tests/services/test_questionnaires.py

Change order of checks for QuestionnairesService.get_session in such a way that already submitted questionnaires cause a HTTP 410, same for expired sessions.

SIG-3938 changed order of get_session checks

---

.github/pull_request_template.md

This will apply for any PR which is opened from another repository.
This adds a checkbox to the PR template so that upstream can make edits to incoming PRs.

Add checkbox about "Allow edits and access to secrets by maintainers"

---

api/app/signals/apps/signals/models/history.py
api/app/tests/apps/api/test_private_signal_endpoint.py

Note: this is precursor to a full implementation of a proper delete
taking into account buisiness rules etc. Current commit only allows
delete at model level and will be used to delete some test Signal
instances using shell access.

Allow Signal delete from django shell.

---

api/app/signals/apps/api/tests/__init__.py
api/app/signals/apps/api/tests/validators/__init__.py
api/app/signals/apps/api/tests/validators/test_extra_properties.py
api/app/signals/apps/api/validators/extra_properties.py

Refactored the ExtraPropertiesValidator and added unit tests

Refactored the ExtraPropertiesValidator and added unit tests

---

api/app/signals/apps/questionnaires/rest_framework/serializers.py
api/app/signals/apps/questionnaires/rest_framework/views/public.py
api/app/signals/apps/questionnaires/tests/rest_framework/views/test_public_sessions_endpoint.py

Draft for questionnaires app API that allows several questions and answers to be retrieved / created at once.

propagate session_service to serializers

---

api/app/signals/apps/services/tests/domain/test_auto_create_children_containers.py

A unittest in our test suite is connecting to an external service, causing unwanted test suite failure when service is unavailable.

SIG-4168 make sure unittests do not connect to external services

---

api/app/signals/apps/reporting/csv/datawarehouse/__init__.py
api/app/signals/apps/reporting/csv/datawarehouse/signals.py
api/app/signals/apps/reporting/csv/datawarehouse/tasks.py
api/app/signals/apps/reporting/management/commands/dumpcsv.py
api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py
api/app/signals/apps/reporting/tests/management/commands/test_command.py

This PR adds the export of the signal notes (as extra csv file) requested by Den Bosch to the dwh export.
The export creates a cvs file in addition to existing files and contains at least the signal_id and notes for that signal. These notes are used to record 'vuurwerk' specific data.

add note export to csv

---

api/requirements.txt

Bumped Pillow to 9.0.0
"PIL.ImageMath.eval in Pillow before 9.0.0 allows evaluation of
arbitrary expressions, such as ones that use the Python exec method."
More info on https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22817

Bumped Pillow to 9.0.0 (CVE-2022-22817)

---

api/requirements.txt

CVE-2021-45115: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.
CVE-2021-45452: Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.
CVE-2021-45116: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was …

Bumped Django 3.2.11 (CVE-2021-45115, CVE-2021-45452 and CVE-2021-45116)

---

api/app/signals/apps/email_integrations/markdown/renderers.py
api/requirements.txt

Bumped mistune to 2.0.1
Affected versions of this package are vulnerable to Cross-site Scripting (XSS) via image link that is not sanitized.

Bumped mistune to 2.0.1

---

api/app/signals/apps/dataset/sources/cbs.py
api/app/signals/apps/dataset/sources/shape.py
scripts/initialize.sh

The Dutch bureau for statistics (Centraal Bureau voor de Statistiek, CBS) periodically publishes new datasets containing municipal and neighborhood map data for the Netherlands. We have the ability to import this data, but that breaks when old datasets are (re)moved by the CBS. This PR contains some small fixes to be able to ingest the newest CBS data.
Because the dataset is too large to just include please test by running the relevant management commands:
```
python manage.py load_areas cbs-gemeente-2021
python manage.py load_areas cbs-wijk-2021
python manage.py load_areas cbs-buurt-2021
```

CBS published a new municipal and neighborhood map data, use it.

---

api/app/signals/apps/dataset/management/commands/load_cbs_for_municipality.py
api/app/signals/apps/dataset/sources/cbs.py
api/app/signals/apps/dataset/sources/shape.py
api/app/signals/apps/dataset/tests/management/commands/test_load_cbs_for_municipality.py

Signalen is set up to load CBS data for municipal borders and neighborhood borders. This PR adds a management command that can extract the neighborhoods for a given municipality identified by its CBS code. These extracted neighborhoods can than be used by the feature of Signalen which automatically assigns a nuisance complaint to an area.

Load neighborhoods from CBS data given CBS code for municipality

---

api/app/signals/apps/email_integrations/templates/email/signal_default.html
api/app/signals/apps/email_integrations/templatetags/location.py
api/app/signals/apps/email_integrations/tests/test_email_templates_address_formating.py
api/app/signals/apps/email_integrations/utils.py

The template filter "format_address" now can work with a Location object or a address dict
TODO: When the location template variable is removed from the context the "format_address" should only accept the address dict instead of a Location OR an address dict.

The template filter "format_address" now can work with a Location object or a address dict

---

api/requirements.txt

Affected versions of this package are vulnerable to Improper Input Validation. When the path to the temporary directory on Linux or macOS contained a space, this would break removal of the temporary image file after im.show() (and related actions), and potentially remove an unrelated file.

Upgrade pillow 9.0.0 -> 9.0.1

---

api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_utils.py
api/app/signals/apps/email_integrations/utils.py

Removed deprecated email template variables from the context (signal, status and location). All tests that relied on these deprecated variables have been fixed. The admin template no longer mention these variables. On the admin page a list of templates specific variables is added for the admin user to see.

Remove deprecated email template variables

---

api/app/signals/apps/api/filters/utils.py
api/app/signals/apps/api/tests/test_filters.py

It was not possible to filter the private Signals list endpoint on `area_type_code=null`, this PR adds that possibility. This is a partial fix for https://github.com/Signalen/frontend/issues/118 As an aside the Signalen frontend must also be changed to not filter on `area_type_code=district` when "Niet bepaald" (not determined) is selected for the Signal area filter.

area_type_code filtering that does not accept 'null' - it should

---

api/app/signals/apps/api/templates/api/swagger/openapi.yaml

Fixed swagger issue, added schema/type to the email preview query param

Fixed swagger issue, added schema/type to the email preview query param

---

api/requirements.txt

Security upgrade oslo.utils from 4.8.0 to 4.8.1
More information: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0718

Security upgrade oslo.utils from 4.8.0 to 4.8.1

---

.github/workflows/build_and_push_docker_image.yml

Added a github action to create a Docker image and push it to the docker registry when a new release is published (will trigger on released and prereleased)
Todo:

Build and push Docker images when a release is published

---

api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_utils.py
api/app/signals/apps/email_integrations/utils.py

Email templates for some VNG administrated Signalen installations need acces to category names. This PR add them.

Add sub/main category name to email context

---

api/app/signals/apps/api/serializers/nested/status.py
api/app/signals/apps/api/tests/test_reaction_request_flow_trigger.py
api/app/signals/apps/email_integrations/tests/test_actions.py
api/app/signals/apps/email_integrations/tests/test_rules.py
api/app/signals/apps/questionnaires/migrations/0008_auto_20220329_1929.py
api/app/signals/apps/questionnaires/models/question.py
api/app/signals/apps/questionnaires/services/reaction_request.py

The label (the real question) of a Question could only hold 255 characters. For the reaction request flow this should be raised to 400. However to be more future proof the max_length is raised to 1000 characters. An additional check has been added to the status update of a Signal to check if the given text only contains 400 characters if the new state is "reaction requested", if it is more a 400 is returned with a response body. Added a migration containing the new max_length and 2 other changes that where not in a migration. Added a test and altered other tests for this change.

SIG-4510 Status update to "reaction requested" should allow 400 characters instead of 200

---

api/app/signals/settings/base.py

Changed the DEFAULT_FROM_EMAIL to "Meldingen gemeente Amsterdam <noreply@meldingen.amsterdam.nl>"

Changed the default for DEFAULT_FROM_EMAIL to "Meldingen gemeente Amsterdam <noreply@meldingen.amsterdam.nl>"

---

api/app/signals/apps/reporting/csv/datawarehouse/locations.py
api/app/signals/apps/reporting/csv/datawarehouse/signals.py
api/app/signals/apps/reporting/csv/utils.py
api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py
api/app/signals/apps/signals/factories/location.py

implements https://github.com/Signalen/product-steering/issues/81
- The native db json operations like 'address__openbare_ruimte' are not stripping '"'. I could not find a nice way to strip this at query time. I've added an optional parameter to the reorder_csv to strip '"' if needed
- I noticed that the json structure of the dummy address factory is inconsistent with the stored json in production. Corrected this also

add user assigned at, add parsed json addresses

---

api/requirements.txt

SQL Injection vulnerabilities found in the Django ORM explain, annotate, aggregate and extra methods. See the following URLs for more information:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28346
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28347

Update Django 3.2.12 -> 3.2.13 (SQL injection vulnerabilities found in the Django ORM)

---

api/app/signals/apps/questionnaires/fieldtypes/__init__.py
api/app/signals/apps/questionnaires/fieldtypes/attachment.py
api/app/signals/apps/questionnaires/models/question.py
api/app/signals/apps/questionnaires/rest_framework/fields.py
api/app/signals/apps/questionnaires/rest_framework/serializers/public/attachment.py
api/app/signals/apps/questionnaires/rest_framework/views/public/sessions.py
api/app/signals/apps/questionnaires/services/session.py
api/app/signals/apps/questionnaires/templates/questionnaires/swagger/public_openapi.yaml
api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_sessions_endpoint.py

To allow the Questionnaire to ask for an attachment a field type is added. An attachment can only be uploaded for an active Session containing a question that allows for an attachment upload.
This PR also contains and is depending on changes in PR https://github.com/Amsterdam/signals/pull/961
TODO:

Upload attachments for a specific Question and Session

---

api/app/signals/settings/base.py

Making new migrations was impossible because the System check framework identified issues in the `django-cors-headers`  configuration. The specific problem if identified can be solved by setting `'null'` as a default in case no allowed origins are configured in the `CORS_ALLOWED_ORIGINS` setting (as described in https://github.com/adamchainz/django-cors-headers/issues/404).

Fix CORS_ALLOWED_ORIGINS default (System check framework was failing)

---

api/app/signals/apps/email_integrations/actions/signal_created.py
api/app/signals/apps/email_integrations/tests/test_actions.py

Fixed 'NoneType' object is not iterable when looping over extra_properties that are none

Fixed 'NoneType' object is not iterable

---

api/app/signals/apps/email_integrations/actions/signal_created.py
api/app/signals/apps/email_integrations/tests/test_actions.py

Fixed a bug when parsing the extra_properties for the signal_created email context. An answer in the extra_properties can also be just a string

Fix parsing extra_properties for email context when sending the signal_created email

---

api/app/signals/apps/signals/migrations/0158_alter_question_field_type.py
api/app/signals/apps/signals/models/question.py

To be able to apply special case logic to the location question (where is the nuisance complaint) we create a special field type. This way we do not have to apply too much fuzzy logic to the AssetSelect questions.

Add Location question field type to VNG style Question model

---

api/app/signals/apps/email_integrations/actions/feedback_received_action.py
api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_actions.py

Add extra feedback parameters for the email template

add extra feedback parameters for the email template

---

api/app/signals/apps/email_integrations/actions/feedback_received_action.py
api/app/signals/apps/email_integrations/tests/test_actions.py
api/app/signals/settings/base.py

Added a feature flag to enable/disable the system mail action for FeedbackReceived

Added a feature flag to enable/disable the system mail action for FeedbackReceived

---

api/app/signals/apps/feedback/serializers.py

Add the feedback save before the sending trigger to use the updated data from the feedback

Save feedback before sending the mail to have the updated data

---

api/app/signals/apps/email_integrations/actions/signal_handeld_negative_contact.py
api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_actions.py

add the feedback context to the new mail action for the email template

add feedback context to the new email rule + unit tests

---

api/app/signals/apps/api/tests/test_history_endpoint.py
api/app/signals/apps/feedback/serializers.py
api/app/signals/apps/feedback/tests/test_feedback.py

Disable the mail when feedback has been received only when the user is satisfied

disabled the mail when the user feedback is_satisfied is True

---

api/app/signals/apps/api/tests/test_private_signal_email_preview_endpoint.py
api/app/signals/apps/api/views/signals/private/signals.py
api/app/signals/apps/email_integrations/utils.py

We were getting inconsistent error messages in the backoffice frontend UI when using the email preview. An email preview could be attempted for a forbidden state transition and that would lead to a no email template present error. The actual problem was that the state transition was not allowed.
This PR matches the  error message for a forbidden state transition in email preview to the normal error message one would get for a forbidden state transition.
(proposed fix for: https://github.com/Signalen/product-steering/issues/139)
TODO:

HTTP 400 response for forbidden status transition in email preview

---

api/app/signals/apps/api/tests/test_public_signal_geography_endpoint.py
api/app/signals/apps/api/views/signals/public/signals.py

Category public_name must be returned in the public signals geography endpoint. When empty or null the Category name must be used as a fallback

fix category public name fallback

---

api/app/signals/apps/api/generics/mixins.py
api/app/signals/apps/api/tests/generics/__init__.py
api/app/signals/apps/api/tests/generics/test_mixins.py

The convert_validation_error function used to convert Django ValidationErrors into DRF ValidationErrors can now handle ValidationErrors with a message OR messages.

convert_validation_error can now handle a ValidationError with a message or messages

---

api/app/signals/apps/api/templates/api/pdf/print_signal.html
api/app/signals/apps/api/views/signals/private/pdf.py
api/app/signals/apps/services/domain/images.py
api/app/signals/apps/services/tests/domain/test_images.py
api/app/signals/apps/sigmax/stuf_protocol/outgoing/pdf.py

The PDFs generated by Signalen do not contain information about the attached images. This PR addresses that and adds a caption to each image with the upload timestamp, the uploader (whether the original reporter or a Signalen user) and the filename.

Add caption to images in PDF (upload timestamp, user and filename)

---

api/app/signals/apps/api/serializers/attachment.py
api/app/signals/apps/api/serializers/signal.py
api/app/signals/apps/api/tests/test_attachment_permissions.py
api/app/signals/apps/api/tests/test_private_signal_endpoint.py
api/app/signals/apps/api/tests/test_private_signal_endpoint_create.py
api/app/signals/apps/api/tests/test_public_signal_endpoint.py
api/app/signals/apps/api/views/attachment.py

The Notes added tot history of a Signal (nuisance complaint) when attachments are deleted must correctly show the active user (and not as part of the notes' text).
see: https://github.com/Signalen/product-steering/issues/176

Correctly set created_by property of Notes for attachment deletes

---

api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_utils.py
api/app/signals/apps/email_integrations/utils.py

Add signal source to e-mail template context, so we can conditionally add some text based on the source.
Requested by municipality Bergen op Zoom.

Add Signal source to e-mail template context

---

api/app/signals/apps/email_integrations/actions/signal_created.py
api/app/signals/apps/services/domain/contact_details.py
api/app/signals/apps/services/tests/domain/test_contact_details.py

Move the contact detail obfuscation code to the services app and add tests.

Move obscuring contact details to services app and add tests

---

api/requirements.txt

CVE-2022-34265: Potential SQL injection via Trunc(kind) and Extract(lookup_name) arguments
More info on:
- https://www.djangoproject.com/weblog/2022/jul/04/security-releases/
- https://security.snyk.io/vuln/SNYK-PYTHON-DJANGO-2940618

CVE-2022-34265: Updated to Django 3.2.14

---

api/requirements.txt

CVE-2022-34749 Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) in the ASTERISK_EMPHASIS regex.
Updated mistune to 2.0.3
More info on:
- https://security.snyk.io/vuln/SNYK-PYTHON-MISTUNE-2940625

CVE-2022-34749: Updated mistune to 2.0.3

---

api/requirements.txt

CVE-2022-2309
Affected versions of this package are vulnerable to NULL Pointer Dereference in the iterwalk() function (used by canonicalize) that can be triggered by malicious input.CVE-2022-2309
Updated lxml to version 4.9.1
More info on:
- https://security.snyk.io/vuln/SNYK-PYTHON-LXML-2940874
- https://www.cve.org/CVERecord?id=CVE-2022-2309

CVE-2022-2309: Updated lxml to version 4.9.1

---

api/app/signals/apps/signals/management/commands/delete_signals.py
api/app/signals/apps/signals/tests/management/commands/delete_signals/test_delete_signals.py
api/app/signals/apps/signals/tests/management/commands/delete_signals/test_delete_signals_base.py

The end status "GESPLITST" has been used in Amsterdam for a small period. Signals that have the status "GESPLITS" are basically parent and child Signals so they also should be deleted after X time.
In this PR the option to delete Signals in the state "GESPLITST" has been added as an option to the "delete_signals" management command.

SIG-4683 Added status "GESPLITST" as an option to the "delete_signals" script

---

api/app/signals/apps/api/serializers/category.py
api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories.json
api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories_{slug}.json
api/app/signals/apps/api/tests/json_schema/get_signals_v1_public_terms_categories_{slug}_sub_categories_{sub_slug}.json
api/app/signals/apps/api/tests/test_public_category_endpoint.py

Added the "is_public_accessible" flag of a category to the response of the public category endpoints.
For a parent category the "is_public_accessible" can be set to True or False. However when there are child categories that have a "is_public_accessible" set to True this will also apply to the parent category.
Examples:
Category list:
```
{
"_links": {
"self": {
"href": "http://127.0.0.1:8000/signals/v1/public/terms/categories"
},
"next": {
"href": null
},
"previous": {
"href": null
}
},
"count": 13,
"results": [
{
"_links": {
"curies": {
"name": "sia",
"href": "http://127.0.0.1:8000/signals/v1/relations"
},
"self": {
"href": "http://127.0.0.1:8000/signals/v1/public/terms/categories/afval"
}
},
"_display": "Afval",
"name": "Afval",
"slug": "afval",
"public_name": null, …
```

SIG-4678 Added "is_public_accessible" flag to the responses of the public category endpoints

---

api/app/signals/apps/email_integrations/actions/signal_created.py
api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
api/app/signals/apps/email_integrations/tests/test_actions.py
api/app/signals/apps/services/domain/contact_details.py

Add the variable reporter allowed sharing to the create signal context to be used in the email templates
Also a small quickfix where @staticmethod was missing for the obscure_phone method

add reporter allowed sharing variable to the create signal template

---

api/requirements.txt

Bumps 
- [Django](https://github.com/django/django) from 3.2.14 to 3.2.15.
Fixes
CVE-2022-36359: Potential reflected file download vulnerability in FileResponse
An application may have been vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename was derived from user-supplied input. The filename is now escaped to avoid this possibility.
This issue has high severity, according to the Django security policy.

Bumped Django from 3.2.14 to 3.2.15

---

api/app/signals/apps/feedback/models.py
api/app/signals/apps/feedback/tests/test_model.py

add enters after each list option in the history

---

api/app/signals/apps/api/templates/api/pdf/print_signal.html

Images in PDFs created from Signals (nuisance complaints) are at times truncated. This was caused by thin and tall images overflowing the page. Proposed fix is a CSS tweak in the intermediate HTML templates used for PDF rendering that resizes images to always fit.
**TODO:**
- ~Check new layout with business representatives of Amsterdam.~

Use object-fit to include thin and tall images in PDFs

---

api/app/signals/apps/questionnaires/tasks.py
api/app/signals/apps/questionnaires/tests/test_tasks.py

It was not possible to schedule the cleaning up of outstanding reaction requests that were open for too long via Django Celery Beat. This was the case because the original Signalen instance in Amsterdam was using an external scheduler (Jenkins calling management commands).
This PR addresses that by adding a Celery task to do the cleaning up. Behind the scenes this test calls the same service as the management command.

Add celery task for cleaning up too-long outstanding reaction requests

---

api/app/signals/apps/reporting/csv/datawarehouse/categories.py
api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py

This PR adds the field deadline and deadline_factor_3 to the categories.csv export.
Closes https://github.com/Signalen/backend/issues/176

Add deadline and deadline_factor_3 to categories CSV export

---

.github/workflows/publish_docker_image.yaml

This is a proposal to start publishing Docker images to GitHub container registry. This allows us to switch from Docker Hub to GitHub container registry. This has the following benefits:
- Better CI + GitHub integration
- Forks are able to reuse this action for creating their own Docker images
- No rate limits

Start publishing Docker images to GitHub container registry

---

api/app/signals/apps/api/tests/test_public_signal_geography_endpoint.py
api/app/signals/apps/api/views/signals/public/signals.py

Closed nuisance complaints and those in non public categories are not correctly filtered. This PR contains failing test, fixes the filtering, and fixes a test that was inappropriately assigning nuisance complaints to main categories (behavior currently not supported by Signalen).

Product steering/250 (Fix public map endpoint filtering)

---

api/app/signals/apps/api/tests/test_serializers.py
api/app/signals/apps/email_integrations/tests/test_actions.py
api/app/signals/apps/questionnaires/rest_framework/views/public/questionnaires.py
api/app/signals/apps/questionnaires/rest_framework/views/public/questions.py
api/app/signals/apps/questionnaires/tests/services/test_questionnaires.py
api/app/signals/apps/questionnaires/tests/services/test_session.py
api/app/signals/apps/services/domain/images.py
api/app/signals/apps/services/tests/domain/test_images.py
api/app/signals/apps/signals/tests/test_models.py

Small clean-up of test-suite runtime warnings. Fixed timezone problems and used `self.assertEqual` in stead of `self.assertEquals`. This silences the majority of warnings caused by our code in the test suite - a number of libraries still cause warnings that need to be fixed in those libraries.

Chore: silence test suite warnings (assertEquals, timezone problems)

---

api/app/signals/apps/signals/management/commands/assign_area.py

Unwanted state changes were observed under load while updating the area_names. This is most likely caused by writing back too much of the Signal model when saving a location update.

Only save location and timestamp to avoid unwanted state changes

---

api/app/signals/apps/reporting/migrations/0004_add_reaction_statusses.py

The ext_tdo view was missing the 'reaction requested' and 'reaction received' state. This PR adds the missing statusses.
Closes https://github.com/Signalen/backend/issues/173

Add missing 'reaction requested' and 'reaction received' status to view

---

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
api/app/signals/apps/api/tests/test_public_signal_geography_endpoint.py
api/app/signals/apps/api/views/signals/public/signals.py

Added additional category information to the properties of the features in the FeatureCollection response of the public signals geography endpoint (SIG-4761 on the Amsterdam JIRA board)
Example response:
```JSON 
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [
4.890986949631043,
52.41875227274259
]
},
"properties": {
"category": {
"name": "Zwerfvuil op straat",
"slug": "zwerfvuil-op-straat",
"parent": {
"name": "afval"
"slug": "afval"
}
},
"created_at": "2022-09-06T00:00:00+00:00"
}
}
]
}
```

Added additional information to the public signals geography response

---

api/app/signals/apps/history/models/log.py
api/app/signals/apps/history/tests/services/test_bug_SIG4789.py

Fixed "Deelmelding toegevoegd" was shown as "Actie onbekend."

Fixed "Deelmelding toegevoegd" was shown as "Actie onbekend."

---

api/app/signals/apps/email_integrations/actions/signal_created.py
api/app/signals/apps/email_integrations/tests/test_action_signal_created_extra_properties.py

If a extra_property answer only contains a location this must be shown as "Locatie gepind op de kaart" in the signal created e-mail.
Example of the extra_property:
```JSON
{
"id": "extra_straatverlichting_nummer",
"label": "Lichtpunt(en) op kaart",
"answer": {
"location": {
"address": {
"postcode": "1016EA",
"huisnummer": "237A",
"woonplaats": "Amsterdam",
"openbare_ruimte": "Keizersgracht"
},
"coordinates": {
"lat": 52.37223359027052,
"lng": 4.884936393337258
}
}
},
"category_url": "/signals/v1/public/terms/categories/wegen-verkeer-straatmeubilair/sub_categories/lantaarnpaal-straatverlichting"
},
```
The generated e-mail:

SIG-4791 extra_property with a location only must be shown as "Locatie gepind op de kaart" in the signal created email

---

api/app/signals/apps/services/domain/dsl.py

This change uses local time instead of UTC time in expressions.

Use local time instead of UTC time in expressions

---

api/requirements.txt

Bumped Django 3.2.16
```
CVE-2022-41323: Potential denial-of-service vulnerability in internationalized URLs
Internationalized URLs were subject to potential denial of service attack via the locale parameter. This is now escaped to avoid this possibility.
This issue has medium severity, according to the Django security policy.
Thanks to Benjamin Balder Bach for the report.
```
More information about this Django update can be found on https://www.djangoproject.com/weblog/2022/oct/04/security-releases/

Bumped Django 3.2.16

---

api/app/signals/apps/reporting/csv/datawarehouse/kto_feedback.py
api/app/signals/apps/reporting/tests/csv/test_feedback_text_or_text_list.py

Since July 2022 the feedback supports multiple answers. The CSV export has a text and a text_list column. Since July the text is no longer used in favour of the text_list. However the datawarehouse did not made the change to use the text_list yet. In this PR the first answer in the text_list is also set as the text if no text is present.

Use the first item from the text_list as text if empty

---

.github/workflows/ci.yml

The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

Updated the ci.yml from ubuntu-18.04 to ubuntu-20.04

---

.github/workflows/build_and_push_to_docker_hub.yml
.github/workflows/build_and_push_to_github_container_registry.yml
.github/workflows/manual_build_and_push_to_docker_hub.yml

This PR refactors the workflow names to make it more clear that they are specific to Docker Hub and GitHub Container Registry. Also the workflows are in line with the frontend, see https://github.com/Amsterdam/signals-frontend/pull/2348

Refactor workflow names

---

api/app/signals/apps/reporting/csv/datawarehouse/locations.py
api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py

The `area_code` and `area_name` fields as used by VNG installations are not part of the CSV dumps, this PR adds them.
(We disregard `_stadsdeel` field which can contain the `area_code` or `stadsdeel` as used in Amsterdam.)

Add area_code and area_name fields to location CSV dumps

---

api/app/signals/settings/base.py

Added the setting "overwrite_files" for the DWH AzureStorage. This settings is default "True" and can be set by the ENV variable "DWH_AZURE_OVERWRITE_FILES". This ensures the same behaviour as the current implementation of the SwiftStorage used in Amsterdam.

Added the setting "overwrite_files" for the DWH AzureStorage

---

api/app/signals/apps/search/tasks.py

Added a celery task to the search app to index all Signals updated in a given date range. This functionality is copied from the elastic_index management command.

Added a celery task to the search app to index all updated Signals in a given date range

---

.github/workflows/build_and_push_to_github_container_registry.yml

This bumps cosign to v1.13.1 and fixes signing Docker images on GitHub container registry.

Bump cosign to v1.13.1

---

api/app/signals/settings/base.py

This change makes sure files are saved using system's standard umask. This is required for network mounts like Azure Files as they do not implement a full-fledged permission system.

Set FILE_UPLOAD_PERMISSIONS to None

---

api/app/signals/apps/my_signals/README.md
api/app/signals/apps/my_signals/rest_framework/serializers/me.py
api/app/signals/apps/my_signals/rest_framework/views/me.py
api/app/signals/apps/my_signals/templates/my_signals/swagger/public_openapi.yaml
api/app/signals/apps/my_signals/tests/rest_framework/views/test_my_signals_logged_in_reporter.py
api/app/signals/apps/my_signals/urls.py

Added endpoint "/my/signals/me" that returns information about the currently logged in Reporter. At this moment the response contains the email address.
GET: `/signals/v1/my/signals/me`
```json
{
"email": "reporter@example.com"
}
```

Added endpoint "/my/signals/me" that returns information about the currently logged in Reporter

---

api/app/signals/apps/services/domain/delete_signals.py
api/app/signals/apps/services/tests/domain/test_delete_signals.py
api/app/signals/apps/signals/management/commands/delete_signals.py
api/app/signals/apps/signals/tasks.py
api/app/signals/apps/signals/tests/test_tasks.py

To schedule deleting too-old closed signals via Celery Beat this PR adds a Celery task and service that allow deletion of old closed signals. This PR furthermore refactors the existing management command to delete signals as well.

Add service and celery task for deleting signals

---

api/app/signals/apps/questionnaires/models/choice.py

Change string representation of choice model to display attribute, thereby making Django admin's questionnaire a little easier to use.

Change string representation of choice to display attribute.

---

docs/topics/signalen-and-standard-for-public-code.md

Work towards #1063
Co-authored-by: Eric Herman  <eric@publiccode.net>
This pull request updates the Standard for Public Code assessment to version 0.4.0.  We would like to have the new requiremetns and what have changed since the last assessment.
N/A

Update Standard for Public Code assessment v.0.4.0

---

api/app/signals/apps/signals/admin/expression.py
api/app/signals/apps/signals/models/routing_expression.py
api/app/signals/apps/signals/signal_receivers.py
api/app/signals/apps/signals/tests/test_signal_receivers.py
api/app/signals/settings/feature_flags.py

This change runs routing expressions also when the Signal location or category changes. 
Also there is a small change that allows seeing and changing the routing expressions order in the admin and sets the default ordering of the RoutingExpression model to the order field.
⚠️ This PR includes functional changes and should be included in the release notes.
Closes https://github.com/Signalen/product-steering/issues/294

Run routing expressions on signal location or category change

---

docs/README.md
docs/topics/routing-rules.md

A part of the discussions around [PR#1120](https://github.com/Amsterdam/signals/pull/1120) was the need to document the behavior of Routing expressions on updates to the underlying nuisance complaint (Dutch: melding). This PR adds that documentation.

Document re-evaluation of routing rules on signal updates

---

api/app/signals/apps/api/filters/signal.py
api/app/signals/apps/api/tests/test_public_signal_geography_endpoint.py
api/app/signals/apps/api/views/signals/public/signals.py
api/app/signals/apps/signals/migrations/0164_materialized_view_public_signals_geography_feature_collection.py
api/app/signals/apps/signals/models/views/__init__.py
api/app/signals/apps/signals/models/views/signal.py
api/app/signals/apps/signals/tasks.py

The "public/v1/signals/geography" endpoint was using a query against the tables containing the signals and all relevant data, it was aggregating the feature collection in postgres. However this was giving performance issues and therefore a materialized view has been created. This materialized view contains all the data needed for the endpoint. Also additional data has been added so that the endpoint can filter. The materialized view is kept in sync by a celery task that is created initially to run every 30th minute of every hour, this can be changed in the Django admin.

Refactor slow performing "V1 public signals geography" endpoint

---

api/app/signals/settings/base.py

Added "Links", "X-API-Version" and "X-Total-Count" to the CORS_ALLOW_HEADERS setting. See https://github.com/adamchainz/django-cors-headers#cors_allow_headers-sequencestr for more information.

Added missing headers to the "CORS_ALLOW_HEADERS" setting

---

api/app/signals/apps/history/services/signal_log.py
api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_sessions_endpoint_forward_to_external.py
api/app/signals/apps/questionnaires/tests/services/test_forward_to_external.py

The timestamp of forwarding a message to external collaborators if different from the timestamp in the confirmation message that points to it later. This PR tests that behavior and adds a fix.

Fix timezone caused problem in reception confirmation messages

---

api/app/signals/settings/base.py

Instead of setting the headers in the `CORS_ALLOW_HEADERS` they should have been set in the `CORS_EXPOSE_HEADERS` setting.
The `CORS_ALLOW_HEADERS` is used for non-standard HTTP headers that you permit in requests from the browser. For more information see https://github.com/adamchainz/django-cors-headers#cors_allow_headers-sequencestr
The `CORS_EXPOSE_HEADERS` is used for extra HTTP headers to expose to the browser. For more information see https://github.com/adamchainz/django-cors-headers#cors_expose_headers-sequencestr

Update cors_expose_headers to make use of them in the client.

---

api/app/signals/apps/email_integrations/tests/test_services.py
api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_sessions_endpoint_forward_to_external.py

Sometimes 2 tests in the questionnaires app where failing because the `MailService._status_actions` had no actions at all. The `TestMailActionsSpecialCasesActions` had 2 tests that where causing this issue to appear sometimes when running in parallel. Therefore the test `TestMailActionsSpecialCasesActions` is removed (also these tests where testing cases that will never happen).

Removed `TestMailActionsSpecialCasesActions` because it was causing issues

---

api/app/signals/apps/signals/migrations/0167_alter_signal_options.py
api/app/signals/apps/signals/models/signal.py

To check that a Signalen user is allowed to update nuisance complaints upon reception of updates from CityControl we add a custom permission. This PR is agains the main branch and is required to be merged for PR #1140 to be able to work. That latter PR checks the new permission.
Note: only the Sigmax system user in a Signalen instance should get this permission

Add a new permission for communication with Sigmax

---

api/app/signals/apps/reporting/csv/datawarehouse/kto_feedback.py
api/app/signals/apps/reporting/csv/datawarehouse/utils.py

The "text_list" was rendered in the following format: `"{""a text with spaces"",nospacesatall,test}"`. This was an issue for the Datawarehouse. With this change the "text_list" is rendered as: `"[""a text with spaces"", ""nospacesatall"", ""test""]"`
Before:
```
2,True,False,a text with spaces,,2023-01-25 08:24:48.100385+00,2023-01-25 09:24:51.498+00,"{""a text with spaces"",nospacesatall,test}"
```
After:
```
2,True,False,a text with spaces,,2023-01-25 08:24:48.100385+00,2023-01-25 09:24:51.498+00,"[""a text with spaces"", ""nospacesatall"", ""test""]"
```

CSV Export for Feedback will now have the "text_list" in the following format: "[""a text with spaces"", ""nospacesatall""]"

---

api/app/signals/urls.py

Currently this button returns a page that cannot be found, and therefore is rather confusing for administrators.

Remove 'view site' button in Django admin, as this link does not work

---

api/app/signals/apps/api/templates/api/swagger/openapi.yaml

When I tried to use the available OpenAPI spec, in conjunction with Gitlab's DAST, I got schema validation errors.
This PR corrects those.
The patched spec has been used as input to Gitlab's DAST scanner.

Correct backend's OpenAPI spec.

---

api/app/signals/apps/sigmax/stuf_protocol/outgoing/stuf.py
api/app/signals/apps/sigmax/tests/stuf_protocol/outgoing/test_stuf.py
api/app/signals/settings/base.py

This PR adds the ability to configure a client certificate (`SIGMAX_CLIENT_CERT`) and key (`SIGMAX_CLIENT_KEY`) that can be used for authenticating to Sigmax or an API gateway that is inbetween.
⚠️ This PR also removes the `verify=False` flag that is currently in the outgoing POST request to Sigmax. Using this flag is considered evil and is not required any more.

Add client certificate / key support for outgoing Sigmax connections

---

api/app/signals/apps/email_integrations/rules/signal_optional.py
api/app/signals/apps/email_integrations/tests/test_actions.py
api/app/signals/apps/email_integrations/tests/test_rules.py

When a Signal status is updated to "INGEPLAND" it should also be possible to send an email if the `send_email` flag is set to `True`. This should trigger the "optional" email action and send the "optional" email template. 
Added the case to the unit tests.

When changing the Signal status to "INGEPLAND" it should be able to trigger the optional email to be send

---

api/app/signals/apps/email_integrations/actions/signal_reopened.py
api/app/signals/apps/email_integrations/tests/test_actions.py

Add additional context to reopened emails.

Add more context to reopened email

---

api/app/signals/apps/reporting/csv/utils.py
api/app/signals/apps/reporting/management/commands/dump_tdo_csv_files.py
api/app/signals/apps/reporting/management/commands/dump_test_csv.py
api/app/signals/apps/reporting/management/commands/dumpcsv.py
api/app/signals/apps/reporting/services/clean_up_datawarehouse.py
api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py
api/app/signals/apps/reporting/tests/csv/test_horeca.py
api/app/signals/apps/reporting/utils.py
api/app/signals/settings/base.py
api/requirements.txt
api/requirements/req-base.txt

SwiftStorage is no longer used by any of the municipalities. 
All municipalities are either using Azure blob storage or a form of local storage that is currently migrated to Azure blob storage. Therefore it was decided to remove SwiftStorage from the code base.

Remove SwiftStorage as it is no longer used

---

api/app/signals/__init__.py

V0 has been removed since 2020 and the V0 version is no longer exposed therefore it could be removed from the API_VERSIONS.

Removed V0 from API_VERSIONS

---

api/app/signals/__init__.py

Removed work-arround that was in place for drf-extensions. This work-arround is no longer needed because drf-extensions fixed the issue.
https://github.com/chibisov/drf-extensions/issues/294

Removed work-arround that was in place for drf-extensions

---

app/signals/apps/signals/migrations/0019_auto_20181009_1321.py
app/signals/settings/base.py

Removed "django.contrib.sites" and all settings. The functionality is not used, therefore it was decided to remove it.
Before deploying this change run the following command:
```
python manage.py migrate sites zero
```
When the command above has not been executed the "django_site" table is still present (and so are the entries in the "django_migrations" table. These should then be removed manually.

Removed "django.contrib.sites" and settings

---

app/signals/settings/base.py

Currently failed e-mail send tasks still show up as SUCCESS in the task results. This PR makes sure failed e-mail send tasks come up as FAILURE. This PR adds the ability to monitor task results.
Note that e-mail tasks that are in a retry state temporarily incorrectly show SUCCESS in the task results. This is due to a [missing raise condition in django-celery-email](https://github.com/pmclanahan/django-celery-email/blob/d47da19c09e29eea90684692e8dfa059e026c046/djcelery_email/tasks.py):
```python
send_emails.retry([[message], combined_kwargs], exc=e, throw=False)
```
should be:
```python
raise send_emails.retry(exc=e)
```
according to the [Celery docs](https://docs.celeryq.dev/en/stable/userguide/tasks.html#retrying).
Not sure if they are willing to fix this in djcelery_email, as reliable …

Mark failed e-mail send tasks as FAILURE

---

app/signals/apps/email_integrations/templates/email/signal_forward_to_external.html
app/signals/apps/email_integrations/templates/email/signal_forward_to_external.txt

Fix typo in signal_forward_to_external default mail

---

app/signals/apps/api/views/signals/private/signals.py

Remove category_assignment__category__parent from select_related list as it produces more queries instead of less.

Remove category_assignment__category__parent from select_related list

---

app/signals/apps/api/fields/category.py

Add parent to select_related in order to reduce the number of queries produced when calling the signals list endpoint.

Add parent to select_related in order to reduce the number of queries

---

.github/workflows/ci.yml
Dockerfile
app/requirements.txt
app/requirements/req-base.txt

Updated the python version to 3.11.
The Dockerfile and Github CI is now based on python 3.11. Added libpq-dev to the Dockerfile, needed for psycopg and updated uWSGI from 2.20.20 to 2.20.21.
🧹 Removed several dependencies from the requirements.txt file that were not being used by the application, including flex, importlib-metadata, jsonpointer, rfc3987, strict-rfc3339, cycler, fonttools, kiwisolver, and numpy.

Upgrade to python 3.11

---

app/requirements.txt
app/requirements/req-base.txt
docker-compose.yml

This PR adds task monitoring using [Flower](https://flower.readthedocs.io/). During local development via Docker compose, Flower is available via:
http://localhost:5566/
For production we can add a deployment to the Helm chart and use the [Prometheus endpoint of Flower](https://flower.readthedocs.io/en/latest/prometheus-integration.html#prometheus-integration) to scrape the metrics.

Add task monitoring using Flower

---

app/signals/apps/api/serializers/nested/category.py
app/signals/apps/api/views/signals/private/signals.py

Use STRING_AGG to concatenate all resonsible department codes in the main queryset used for the v1 private signals endpoints.
Made sure that this change is backwards compatible because in the v1 public signals endpoints this serializer is used without the data from a queryset.

Concatenate the responsible department codes on the V1 private signals endpoints

---

app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
app/signals/apps/email_integrations/tests/test_utils.py
app/signals/apps/email_integrations/utils.py

Added the incident date start to the general email context

Added the incident date start to the general email context

---

app/signals/apps/api/serializers/nested/category.py
app/signals/apps/api/serializers/nested/reporter.py
app/signals/apps/api/views/signals/private/signals.py

Reverted the latest 2 query enhancments. Unfortunately these changes had a negative effect.
Reverted changes:
- Nested reporter serializer, the "allows_contact" field
- Nested category serializer, the "departments" field

Revert the latest query enhancments

---

app/signals/apps/api/serializers/category.py
app/signals/apps/api/tests/test_private_category_endpoint.py

Add api support for the new main category configuration object.

Main category configuration in api

---

app/signals/apps/signals/tasks.py
app/signals/apps/signals/tests/test_task_anonymize_reporters.py

There are several cases in which reporters should have been anonymized, but unfortunately they have not.
This PR aims to solve the issue.

Not all reporters are anonymized while they should be

---

app/signals/apps/signals/models/status_message.py

Override __str__ method to display the title in admin list

Override __str__ method to display the title in admin list

---

app/signals/apps/api/serializers/category.py

When a category icon is removed the history endpoint for categories cannot currently handle that case.
This PR adds support for presenting icon removals in the category history endpoint.

Add case for presenting icon removal in history of category

---

app/signals/apps/signals/tasks.py
app/signals/settings/base.py
docker-compose.yml

Set lowest priority for the `anonymize_reporters` and the `anonymize_reporter` tasks and updated rabbitmq image.
Added the `CELERY_TASK_DEFAULT_PRIORITY` setting with a default value of `5` to control the priority of tasks in Celery. Updated the `anonymize_reporters` and the `anonymize_reporter` tasks to run with priority `0` to prevent them from clogging up the queue. Also, changed the RabbitMQ image from 3.8 to 3.8-management to allow easier management and monitoring of the RabbitMQ server.

Celery tasks "anonymize_reporters" and "anonymize_reporter" should run with the lowest priority

---

app/signals/apps/api/serializers/category.py
app/signals/apps/api/templates/api/swagger/openapi.yaml

Add main category configuration field to public endpoint

Add main category configuration field to public endpoint

---

app/signals/apps/api/tests/test_public_signal_endpoint.py
app/signals/apps/api/views/signals/public/signals.py

Refactor PublicSignalViewSet to support signal creation and retrieval
- Modified PublicSignalViewSet to inherit from CreateModelMixin and RetrieveModelMixin
- Removed unnecessary code
- Updated method docstrings to provide clear explanations
- Added type hints for parameters and return values
- Updated one unit test

Refactor PublicSignalViewSet to support signal creation and retrieval

---

app/signals/apps/api/filters/status_messages.py
app/signals/apps/api/templates/api/swagger/openapi.yaml
app/signals/apps/api/tests/test_status_message_endpoint.py
app/signals/apps/api/views/status_message.py
app/signals/apps/signals/factories/status_message.py

In this PR the `StatusMessageViewSet` is updated to support the list functionality. 
The list is ordered by default using "-created_at" and can be ordered by giving the "order_by" query parameter for: "created_at", "updated_at", "active" and "state". Adding a "-" will invert the ordering. It is also possible to filter the results on: "state", "category_id" and "active". Both "state" and "category_id" are multiple choice.
Fixed a small bug in the `StatusMessageFactory`, the `FuzzyChoice` for `state` was giving tupples instead of the actual value that should be stored in the database.

Added list support to the StatusMessageViewSet

---

app/signals/apps/api/tests/test_private_area_endpoint.py
app/signals/apps/api/tests/test_public_area_endpoint.py
app/signals/apps/api/views/area.py

Refactored the `PublicAreasViewSet` and `PrivateAreasViewSet` to use the standard DRF `ListModelMixin` and `GenericViewset` instead of the `DatapuntViewSet`.

Refactored the PublicAreasViewSet and PrivateAreasViewSet

---

app/signals/apps/api/views/departments.py

Refactored the PrivateDepartmentViewSet to use the standard DRF mixins and ReadOnlyModelViewSet instead of the DatapuntViewSet.

Refactored the PrivateDepartmentViewSet

---

app/requirements.txt

Bumped django-storages from 1.12.3 to 1.13.2
In version 1.13.2 an issue with uploading files and the use of `AZURE_CUSTOM_DOMAIN` has been fixed, more info about this bug can be found on https://github.com/jschneier/django-storages/issues/1116

Bumped django-storages from 1.12.3 to 1.13.2

---

app/requirements/requirements.txt
app/requirements/requirements_dev.txt
app/requirements/requirements_test.in
app/requirements/requirements_test.txt

Removed `pytest-forked` (it is not used) to fix the dependabot alerts about the `py` package (https://github.com/Amsterdam/signals/security/dependabot/39 and https://github.com/Amsterdam/signals/security/dependabot/40). The `py` package is not maintained and the last release is from november 2021.
This commit also updated a couple of other requirements:
- pypdf==3.9.0
- pytest-xdist==3.3.1

Fixing dependabot alerts

---

app/signals/apps/api/tests/test_private_category_endpoint.py
app/signals/apps/api/tests/test_private_signal_endpoint.py
app/signals/apps/api/tests/test_private_signal_endpoint_create.py
app/signals/apps/api/tests/test_public_signal_endpoint.py
app/signals/apps/api/tests/test_signal_context_view.py
app/signals/apps/api/tests/test_stored_signal_filters_endpoint.py
app/signals/apps/email_integrations/tests/test_utils.py
app/signals/apps/users/tests/rest_framework/test_users.py
app/signals/apps/users/tests/test_backend.py
app/signals/auth/tests/test_backend.py

Removed unit tests that are skipped or marked with expectedFailure

Removed unit tests that are skipped or marked with expectedFailure

---

app/requirements/requirements.txt
app/requirements/requirements_dev.txt
app/requirements/requirements_test.txt

Bumped requests and typing-extensions

Bumped requests and typing-extensions

---

app/signals/apps/api/serializers/status_message.py
app/signals/apps/api/templates/api/swagger/openapi.yaml
app/signals/apps/api/tests/test_status_message_endpoint.py
app/signals/apps/api/urls.py
app/signals/apps/api/views/status_message.py

Added a new endpoint that allows a user to set the position for all status_messags connected to a specific category

status messages ordering

---

app/signals/apps/api/filters/status_messages.py
app/signals/apps/api/templates/api/swagger/openapi.yaml
app/signals/apps/api/views/status_message.py

The category filter should be a choice instead of multiplechoice + added ordering on position in the filtered category

Fixed category filter and ordering for the status messages endpoint

---

docs/adr/0005-generate_openapi_spec_using_drf-spectacular.md

Added an ADR containing the decision to use drf-spectacular for OpenAPI spec generation

Added an ADR containing the decision to use drf-spectacular

---

app/signals/apps/api/apps.py
app/signals/apps/api/fields/attachment.py
app/signals/apps/api/fields/category.py
app/signals/apps/api/fields/signal.py
app/signals/apps/api/generics/pagination.py
app/signals/apps/api/serializers/signal_context.py
app/signals/apps/api/urls.py
app/signals/apps/api/views/attachment.py
app/signals/apps/api/views/category_removed.py
app/signals/apps/api/views/signals/private/signal_context.py
app/signals/apps/api/views/signals/private/signals.py
app/signals/apps/api/views/signals/private/signals_promoted_to_parent.py
app/signals/apps/my_signals/rest_framework/views/signals.py
app/signals/apps/search/rest_framework/pagination.py
app/signals/auth/schema.py
app/signals/schema.py
app/signals/settings/base.py

Add/Fix the OpenAPI specs generation for the `v1/private/signals` endpoints using drf-spectacular.
Introducing the necessary decorators, extend_schema_view, extend_schema, and extend_schema_field, to generate OpenAPI specifications correctly. The get_paginated_response_schema for HALPagination has been overridden to make sure the correct documentation is generated. Additionally, the JWTAuthBackend schema has been properly implemented to generate the correct authentication information for the API.
TODO:

drf-spectacular private signals endpoint(s)

---

app/signals/apps/search/rest_framework/serializers.py

Currently when Elasticsearch only returns a highlight for either a title or a text we get a 500 Internal Server Error.
Obviously it should be possible to only have a highlight in just one of the fields, but I missed that case when manually testing before.

Do not require highlights for both title and text fields

---

app/signals/apps/api/serializers/nested/status.py
app/signals/apps/api/serializers/signal.py
app/signals/apps/api/views/attachment.py
app/signals/apps/api/views/signals/public/signals.py
app/signals/apps/api/views/signals/public/signals_map.py

Add/Fix the OpenAPI specs generation for the v1/public/signals endpoints using drf-spectacular.
Adding the necessary decorators, extend_schema_view, extend_schema, and extend_schema_field, to generate the OpenAPI specifications correctly.

Add/Fix the OpenAPI specs generation for the v1/public/signals endpoints using drf-spectacular

---

app/signals/apps/api/fields/category.py
app/signals/apps/api/serializers/category.py
app/signals/apps/api/views/category.py

Add/Fix the OpenAPI specs generation for the public and private category endpoints using drf-spectacular.
Adding the necessary decorators, extend_schema_view, extend_schema, and extend_schema_field, to generate the OpenAPI specifications correctly.

Add/Fix the OpenAPI specs generation for the public and private category endpoints using drf-spectacular

---

app/signals/apps/users/rest_framework/fields/user.py
app/signals/apps/users/rest_framework/serializers/profile.py
app/signals/apps/users/rest_framework/serializers/user.py
app/signals/apps/users/rest_framework/views/permission.py
app/signals/apps/users/rest_framework/views/role.py
app/signals/apps/users/rest_framework/views/user.py
app/signals/schema.py

Add/Fix the OpenAPI specs generation for the v1 private users/roles/permissions endpoints using drf-spectacular.
Added the DatapuntLinksFieldFix that will fix the schema representation of the LinkField from the datapunt_api package.

Add/Fix the OpenAPI specs generation for the v1 private users/roles/permissions endpoints using drf-spectacular

---

app/signals/apps/my_signals/rest_framework/fields/signals.py
app/signals/apps/my_signals/rest_framework/views/me.py
app/signals/apps/my_signals/rest_framework/views/signals.py
app/signals/settings/base.py

Add/Fix the OpenAPI specs generation for the public and private my-signals endpoints using drf-spectacular.

Add/Fix the OpenAPI specs generation for the public and private my-signals endpoints using drf-spectacular

---

app/signals/apps/reporting/csv/datawarehouse/tasks.py

Currently the backend None is used which results in the following error when saving and zipping CSV files:
```
Arguments: {'hostname': 'celery@backend-celery-worker-547d5cdf5f-j8xgl', 'id': '6ea52e33-dccc-4256-84e6-aee79e01467c', 'name': 'signals.apps.reporting.csv.datawarehouse.tasks.save_and_zip_csv_files_endpoint', 'exc': "ImproperlyConfigured('None not present in the AZURE_CONTAINERS settings')"
```

Use correct backend when saving and zipping CSV files for endpoint

---

app/signals/apps/api/app_settings.py
app/signals/apps/api/validation/address/pdok.py
app/signals/settings/base.py

The PDOK Locationservice has been migrated and is available on a new URL, the old URL will no longer work after the 1st of august 2023. More information can be fount at https://www.pdok.nl/-/migratie-pdok-locatieserver-naar-het-nieuwe-3g-platform-afgerond.
This PR makes the PDOK suggest endpoint configurable, and has the default value set to the new URL.

Make the PDOK suggest endpoint configurable with a default to the new URL

---

app/signals/apps/email_integrations/actions/abstract.py
app/signals/apps/email_integrations/actions/assigned_action.py
app/signals/apps/email_integrations/actions/feedback_received_action.py
app/signals/apps/email_integrations/actions/forward_to_external_reaction_received.py
app/signals/apps/email_integrations/actions/signal_created.py
app/signals/apps/email_integrations/actions/signal_forward_to_external.py
app/signals/apps/email_integrations/actions/signal_handeld.py
app/signals/apps/email_integrations/actions/signal_handeld_negative_contact.py
app/signals/apps/email_integrations/actions/signal_optional.py
app/signals/apps/email_integrations/actions/signal_reaction_request.py
app/signals/apps/email_integrations/actions/signal_reaction_request_received.py
app/signals/apps/email_integrations/actions/signal_reopened.py
app/signals/apps/email_integrations/actions/signal_scheduled.py
app/signals/apps/email_integrations/renderers/__init__.py
app/signals/apps/email_integrations/renderers/email_template_renderer.py
app/signals/apps/email_integrations/services.py
app/signals/apps/email_integrations/tests/test_action_signal_created_extra_properties.py
app/signals/apps/email_integrations/tests/test_actions.py
app/signals/apps/my_signals/mail.py

Isolate the email template rendering logic and re-use it. Refactor to include type hints.

Isolate email template rendering

---

app/signals/apps/email_integrations/models.py
app/signals/apps/email_integrations/tests/test_email_templates.py

Adding support for sending an email when the reporter was successfully updated.

Add email template support for sending confirmation mail

---

app/signals/apps/reporting/csv/datawarehouse/kto_feedback.py
app/signals/apps/reporting/csv/datawarehouse/utils.py

Moved the 'to_jsonb' functionallity into Feedback query within 'create_kto_feedback_csv', remove unused 'utils.py' file for improved code organization and clarity

Moved the 'to_jsonb' functionallity into Feedback query within 'create_kto_feedback_csv'

---

app/signals/apps/api/serializers/status_message.py
app/signals/apps/api/tests/test_status_message_endpoint.py

Update/Remove categories from a status-message when creating and updating them + updated/added unit tests

Add/Remove categories on a StatusMessage

---

app/signals/settings/base.py

Allow setting cookie domain, in order for our session cookie to be valid for subdomains.

Allow setting cookie domain

---

app/signals/apps/signals/models/reporter.py
app/signals/apps/signals/tests/test_reporter_state_machine.py

Implementation of the cancel transition in the state machine for updating the reporter information.

Implement reporter cancel transition

---

app/signals/settings/base.py

This sets a default value of 5 seconds to EMAIL_TIMEOUT, so sending mails can actually time out. The [default setting is None](https://docs.djangoproject.com/en/3.2/ref/settings/#email-timeout).

Set default value of 5 to EMAIL_TIMEOUT

---

app/signals/apps/signals/models/reporter.py
app/signals/apps/signals/tests/test_reporter_state_machine.py

Send confirmation email when not original reporter and when email address is available

Send confirmation email when not original reporter and when email address is available

---

app/signals/apps/api/serializers/signal_reporter.py
app/signals/apps/api/templates/api/swagger/openapi.yaml

Make token expires field available in api response

Make token expires field available in api response

---

app/signals/apps/api/serializers/signal_reporter.py

Make create() atomic so that cancellation of previous reporter is rolled back in case transitions fail due to the optimistic locking protection: https://github.com/viewflow/django-fsm#optimistic-locking.

Make create() atomic so that cancellation of previous reporter is rolled back in case transitions fail

---

app/signals/apps/api/serializers/area.py
app/signals/apps/api/views/area.py

Add drf-spectacular schema extension to improve API documentation for private and public Area endpoints:
- /signals/v1/public/areas/
- /signals/v1/public/areas/geography
- /signals/v1/private/areas/
- /signals/v1/private/areas/geography

Add drf-spectacular schema extension to improve API documentation for private and public Area endpoints

---

app/signals/apps/api/serializers/departments.py
app/signals/apps/api/views/departments.py

Add drf-spectacular schema extension to improve API documentation for private Department (CRU) endpoint

Add drf-spectacular schema extension to improve API documentation for private Department endpoint

---

app/signals/apps/api/views/expression.py
app/signals/apps/api/views/questions.py
app/signals/apps/search/rest_framework/views.py

Refactored DataPuntViewSet and DataPuntViewSetWritable to the correct DRF and DRF extensions classes

Refactored: No longer use DataPuntViewSet and DataPuntViewSetWritable

---

app/signals/apps/feedback/rest_framework/serializers.py

Fixed issue in storing the Feedback text_list in the order it was provided

Fixed issue in storing the Feedback text_list

---

app/signals/urls.py

the use of url('') is deprecated changed to re_path('') when declaring the endpoint for the markdownx urls

url('') is deprecated changed to re_path('')

---

app/signals/apps/signals/tests/test_models.py

assertEquals is deprecated, changed the remainig assertEquals into assertEqual

assertEquals is deprecated, changed the remainig assertEquals into assertEqual

---

app/signals/settings/base.py

Make email max retries and retry delay configurable. Instead of the proposed change in https://github.com/Amsterdam/signals/pull/1328 prefer not setting the configuration values unless explicitly overridden by the env vars.

Make email max retries and retry delay configurable

---

app/signals/apps/api/generics/permissions.py
app/signals/apps/api/serializers/signal_reporter.py
app/signals/apps/api/tests/test_private_signal_reporters.py
app/signals/apps/api/views/signals/private/signal_reporters.py

Allow cancelling a reporter through an API endpoint.

Reporter cancel endpoint

---

app/signals/apps/my_signals/rest_framework/views/signals.py

Currently a reporter can see the communication with external parties in the "my signals" signal history.
This is undesirable and this PR makes sure that no longer happens.

Do not display history about externals

---

app/signals/apps/history/services/signal_log.py
app/signals/apps/questionnaires/tests/services/test_forward_to_external.py

Do not display external email address in history.

Do not display external email address in history

---

app/signals/apps/api/views/status_message.py
app/signals/apps/search/signal_receivers.py
app/signals/apps/search/tasks.py

Synchronously update status messages index instead of asynchronously using celery.

Synchronously update status messages index

---

app/signals/apps/search/signal_receivers.py

Force elasticsearch index to refresh on changes to status messages

Force elasticsearch index to refresh on changes to status messages

---

app/logs/config.py
app/requirements/requirements.in
app/requirements/requirements.txt
app/requirements/requirements_dev.txt
app/requirements/requirements_test.txt
app/signals/settings/base.py

Since we no longer use Sentry and it was confirmed that other municipalities also no longer use Sentry, we're dropping Sentry support with this PR.

Remove raven dependency

---

app/signals/apps/signals/migrations/0195_auto_20230821_1059.py

The current data migration logic is incorrect. I assumed that the created_by value would be the email address of the reporters, but it turns out that is not the case.

Attachments uploaded by reporters have no created_by value

---

app/signals/apps/api/serializers/attachment.py
app/signals/apps/api/tests/test_public_signal_endpoint.py

Set public to true by default for attachments uploaded using the public endpoint.

Set public to true by default for attachments uploaded using the public endpoint

---

app/signals/apps/my_signals/rest_framework/fields/signals.py
app/signals/apps/my_signals/tests/rest_framework/views/test_my_signals_detail.py

Display only public attachments in my signals and include caption field in output.

Only public attachments in my signals with caption field included

---

app/signals/apps/search/documents/status_message.py
app/signals/settings/base.py

We would like to propose to make the new status messages index name configurable, as the other Signalen municipalities typically share one Elasticsearch cluster for multiple environments (acceptance, production).
By making the status message index name configurable, we support this deployment scenario.

Make status messages index configurable

---

app/signals/apps/search/elasticsearch_dsl/search.py
app/signals/apps/search/management/commands/delete_status_messages_index.py

We would like to propose to make the new status messages index name configurable, as the other Signalen municipalities typically share one Elasticsearch cluster for multiple environments (acceptance, production).
By making the status message index name configurable, we support this deployment scenario.
In addition to #1362 we found two other hardcoded references to "status_messages". This PR also makes these configurable.

Make status messages index configurable (part 2)

---

.dockerignore

Ignore dumps folder to save time/memory when building container images

Ignore dumps folder to save time/memory when building container images

---

app/signals/apps/signals/apps.py
app/signals/apps/signals/models/permission.py

This commit adds a new abstract class, CustomPermission, essential for creating custom permissions independent of existing models, as Django auth Permissions necessitate a ContentType association. Additionally, a sync_custom_permission function is included, which responds to the DjangoSignal post_migrate, facilitating the creation of custom permissions if they do not already exist.
- [ X No iSort, Flake8 and SPDX issues are present in the code

Introduce CustomPermission abstract class and sync_custom_permission function + custom i18next permission

---

app/signals/apps/api/generics/permissions.py
app/signals/apps/api/tests/test_translation_endpoints.py
app/signals/apps/api/urls.py
app/signals/apps/api/views/translations.py
app/signals/apps/signals/models/permission.py
app/signals/apps/users/tests/rest_framework/test_permissions.py

Added I18Next translation file creation (private) and retrieval (public) views
- Added a `PrivateCreateI18NextTranslationFileView` class to create/update the I18Next translation file from JSON data
- Added a `PublicRetrieveI18NextTranslationFileView` class to retrieve the latest I18Next translation file
- Updated the `urls.py` file to include public and private endpoints for translation file management

Added I18Next translation file creation (private) and retrieval (public) views

---

app/signals/apps/api/views/translations.py

Due to Azure's limitations, we are unable to overwrite the translation file directly. To work around this, we delete the existing file before uploading the updated version.

Delete translation file before uploading the updated version

---

Dockerfile
docker-compose.test.yml

Add build stage for building container image to run tests in.

Add test container build stage

---

app/signals/apps/api/generics/permissions.py
app/signals/apps/api/tests/scenarios/context/user.py
app/signals/apps/api/tests/test_private_signal_reporters.py

Implemented 'sia_can_view_contact_details' permission check on signal reporter endpoints and updated/added tests

Implemented 'sia_can_view_contact_details' permission check on signal reporter endpoints

---

docker-compose.yml

Limit elasticsearch heap to 4gb.

Limit elasticsearch heap to 4gb

---

app/signals/admin/oidc/backends.py
app/signals/admin/oidc/tests/test_backends.py
app/signals/admin/oidc/views.py
app/signals/urls.py

Small refactor of the OIDC admin
- Removed the `views.py` and now use the TemplateView for the url path `signals/oidc/login_failure/`
- Removed the `update_user` method of the `AuthenticationBackend`. It is already defined (the same way) in the mozilla_django_oidc `OIDCAuthenticationBackend` https://github.com/mozilla/mozilla-django-oidc/blob/main/mozilla_django_oidc/auth.py#L112
- Added tests to get 100% coverage

Small refactor of the OIDC admin

---

app/signals/apps/history/models/log.py

The recently added asserts seem to be causing some issues with the history of older signals, for some reason `self.object` is not always available in those cases. This PR moves the asserts to exactly where they are required in order to prevent that case.

Move asserts to the lines where they are required

---

app/signals/admin/oidc/backends.py
app/signals/admin/oidc/tests/test_backends.py
app/signals/settings.py

Added the `OIDC_CREATE_USER` setting (set to `False`) to prevent user creation. This commits also removes the custom code that was created to prevent this behaviour. This change is made in accordance with the `mozilla-django-oidc` the [documentation](https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#preventing-mozilla-django-oidc-from-creating-new-django-users).

Added the `OIDC_CREATE_USER` setting to prevent user creation by the `mozilla-django-oidc` package

---

app/signals/apps/sigmax/stuf_protocol/incoming/actualiseerZaakstatus_Lk01.py
app/signals/apps/sigmax/tests/stuf_protocol/incoming/test_actualiseerZaakstatus_Lk01.py
app/signals/apps/sigmax/tests/xxe_test_file.txt

The lxml `etree.fromstring()` function has a security risk of XXE attacks. A custom XML parser is now used that disables resolving entities and blocks network access.

Sigmax, fix for XML external entity expansion

---

app/signals/apps/email_integrations/actions/assigned_action.py
app/signals/apps/email_integrations/tests/test_action_assigned.py

For some e-mail providers (like the REST backend and django-o365mail) adding a full name to a recipient seems to be not supported and results in an error:
```
File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 754, in _internal_request
response.raise_for_status()  # raise 4XX and 5XX error codes.
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/noreply@municipality.nl/sendMail
```
Therefore I propose to omit the full name from the recipients list.
- https://github.com/evyd13/django-o365mail/blob/main/src/django_o365mail/backend.py#L113
- …

Do not include full name in assigned e-mail notification

---

Caddyfile
app/signals/throttling.py
docker-compose.yml

Add logging to see the result of the throttle mechanism. As well as adding an optional reverse proxy to the local development setup.

Throttling not working correctly

---

app/signals/throttling.py

In this commit the `get_ident` method, in the `PostOnlyNoUserRateThrottle` class, is updated to ensure that the identification string is stripped of the colon and port number

Throttling ident fix

---

app/signals/settings.py
docker-compose/scripts/initialize.sh

Use the database cache backend instead of the local memory cache backend. We need this in order for the api request throttling to work correctly.

Use database cache backend

---

app/signals/apps/search/apps.py
app/signals/apps/search/settings.py
app/signals/settings.py

We had some issues with management commands failing due to a request timeout in the Elasticsearch library. In particular:
```python manage.py delete_status_messages_index```
and
```python manage.py init_status_messages_index```
This PR adds an environment variable that changes the timeout of elasticsearch requests.The previous default of 10 seconds is now explicitly configured in the Signalen code instead of using the default value from the Elasticsearch library.
Tested on the Delta10 cluster in a production environment.

Add configurable timeout to search app

---

app/signals/apps/api/tests/test_private_area_endpoint.py
app/signals/apps/api/views/area.py

Added ordering on the areas public and private endpoint + by default order on _type,name + added tests

Added ordering on the areas public and private endpoint

---

README.md
docs/CONTRIBUTING.md

As stated in the email ( https://lists.publiccode.net/hyperkitty/hyperkitty/list/signalen-discuss@lists.publiccode.net/thread/5Y3FFBD7CBP4A4766HWD7N7EVICRZJ4R/ ) the Foundation for Public Code will be winding down the office in Europe, and therefore, we will no longer be able to steward the Signalen codebase to the level which we aspire.

Discontinuing stewardship by Foundation for Public Code

---

app/signals/apps/feedback/models.py

Added/updated the help text on the "reopens_when_unhappy" and "open_answer" attributes of the StandardAnswer model.

Added/updated help text on the StandardAnswer model

---

app/signals/apps/api/serializers/nested/status.py
app/signals/apps/api/tests/test_reaction_request_flow_trigger.py
app/signals/apps/questionnaires/models/question.py

We've been requested to raise the maximum number of characters for the message which is sent when a response is requested of the reporter from 400 characters to 1000 characters.
In the past this has already made possible in the  database model, now the validation will also allow it.

Allow the maximum number of characters

---

Dockerfile

Yesterday I received the following e-mail from Microsoft:
> In July 2024, we’ll begin updating Azure Database for PostgreSQL Flexible Server to use TLS certificates from [Microsoft RSA Root Certificate Authority 2017](https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt). If your apps use certificate pinning, you’ll need to update your trusted root store to accept this root CA in addition to existing  [DigiCert Global Root CA](https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem).
The Microsoft RSA Root Certificate Authority 2017 is not included in Debian Buster. Also the LTS of Debian Buster [expires on June 30th 2024](https://wiki.debian.org/LTS). So I think the best way to solve these problems, is to upgrade to Debian Bookworm.

Upgrade to Debian Bookworm

---

app/signals/settings.py

safely check if user attribute is inside a request

---

app/signals/apps/search/signal_receivers.py
app/signals/apps/search/tests/__init__.py
app/signals/apps/search/tests/test_signal_receivers.py
app/signals/apps/signals/models/reporter.py
docker-compose.test.yml

Currently the elastic search index is not updated when a reporter is anonymized. This PR aims to resolve that problem by sending a Django signal and handling it in a receiver that triggers a celery task to re-index the signal in the elastic search index.

Elastic search index not updated when reporter is anonymized

---

app/signals/apps/api/ml_tool/client.py

Make sure we send `application/json` in the `Content-Type` header, it seems the old Flask version of the legacy classification API was less strict about that.

Make sure we send `application/json` in the `Content-Type` header

---

app/signals/settings.py

Setting `EMAIL_TIMEOUT` currently always results in an exception:
```
ile "/usr/local/lib/python3.11/socket.py", line 845, in create_connection
sock.settimeout(timeout)
TypeError: 'str' object cannot be interpreted as an integer
```
This is because `EMAIL_TIMEOUT` is expected to be an integer, not a string. This changes both `EMAIL_PORT` and `EMAIL_TIMEOUT`.

fix: cast EMAIL_PORT and EMAIL_TIMEOUT to int

---

app/signals/apps/history/services/signal_log.py
app/signals/apps/questionnaires/tests/services/test_forward_to_external.py

Do not store email address of external party in history

Do not store email address of external party in history

---

app/signals/apps/signals/models/status.py

We need to add `straatnotes` as a valid value for the `target_api` field in order for them to be able to set signals to state `ready to send` so that they can then set the state to `sent`.

Add SAOA (straatnotes) to valid `target_api` values

---

app/signals/apps/api/tests/test_private_signal_endpoint.py
app/signals/apps/users/factories.py
app/signals/auth/backend.py
app/signals/auth/tests/test_backend.py
app/signals/test/utils.py

make sure that authenticate function filters on is_active column

---

app/signals/auth/backend.py

fixes login flow by checking if returned user is_active
