Amsterdam/signals

api/src/signals/serializers.py, api/src/signals/tests/test_post_api.py
…ndpoint. Fixed image validation error.
=> Fixed image upload bug on POST /signals/signal/ endpoint (multipart post)

api/src/signals/serializers.py
Fixed image upload size for signal create endpoint (same as image endpoint).
=> Fixed image upload size

api/requirements-root.txt, api/requirements.txt, api/src/signals/__init__.py, api/src/signals/celery.py, api/src/signals/settings.py, docker-compose.yml
- django celery beat 
- django celery results
=> Django Celery

docker-compose.yml
=> mount local datapunt.key to dev database

api/app/signals/apps/signals/urls.py, api/app/signals/apps/signals/views.py, api/app/signals/apps/users/__init__.py, api/app/signals/apps/users/config.py, api/app/signals/apps/users/urls.py, api/app/signals/apps/users/views.py, api/app/signals/settings/base.py, api/app/signals/settings/testing.py, api/app/signals/urls.py, api/app/tests/apps/users/factories.py, api/app/tests/apps/users/test_views.py, api/app/tests/test_api.py, api/app/tests/test_filtering.py, api/app/tests/test_post_api.py
- Moved endpoint `/signals/auth/me/` to `/signals/user/auth/me/`
- Moved logic to it's own Django app named `users`
- Added unit tests for this endpoint
- Changed auth behaviour in unit tests, by default you're not authenticated. You can enable/force authentication with the DRF Test class helper `force_authenticate(user=user)`
=> SIG-519 move auth me endpoint

README.md
only change is to document correct options for running and testin
=> SIG-408 installation/running instructions updated

api/app/signals/apps/signals/fields.py, api/app/signals/apps/signals/permissions.py, api/app/signals/apps/signals/serializers.py, api/app/signals/apps/signals/urls.py, api/app/signals/apps/signals/views.py, api/app/tests/apps/signals/test_api_endpoints.py, api/app/tests/apps/signals/test_filters.py, api/app/tests/apps/users/factories.py, api/app/tests/apps/users/test_views.py
- create new endpoint `/signals/auth/priority/`
=> SIG-596 endpoint priority

api/app/signals/apps/sigmax/views.py, api/app/tests/apps/sigmax/test_soap.py
=> SIG-740 update status text to resultaat: reden for Sigmax terugmelding

api/app/signals/apps/sigmax/templates/sigmax/pdf_template.html
=> SIG-762 opmerking in PDF over missende foto

api/app/signals/__init__.py
Note:
- minor version nump in v1 API as well to 1.1.0
=> Version bump to 0.5.2

api/app/tests/apps/email_integrations/integrations/test_core.py
Added unit test to check the TXT and HTML body of the email
=> Added unit test to check the TXT and HTML body of the email

api/app/signals/__init__.py
Changes
- added documentation for the VNG ZDS 2.0 - SIA integration project
- HTML emails with usabilla links for final mail
- fix datetime to be present in emails
=> Version bump to 6.0.1

api/app/signals/apps/signals/models.py, api/app/signals/apps/signals/pdf/mixins.py, api/app/signals/apps/signals/pdf/views.py, api/app/signals/apps/signals/serializers.py, api/app/signals/apps/signals/templates/signals/pdf/print_signal.html, api/app/signals/apps/signals/urls.py, api/app/signals/apps/signals/views.py, api/app/tests/apps/signals/test_pdf.py
DO NOT MERGE YET
PDF Generation
TODO:
- Add history to the PDF
=> SIG-802 PDF Generation

api/app/signals/__init__.py
=> Revert "Version bump to version 0.7.1"

api/app/signals/apps/signals/migrations/0027_SIG858.py, api/app/tests/apps/signals/test_api_v1_endpoints.py
SIG-858 Added new main and sub categories
TODO:
- Add the correct handling and departments to the sub category
- Update the health check (fixture) after adding the new categories
=> [WIP] feature/SIG-858

api/app/signals/__init__.py
Version bump for production release
=> Version bump to 0.9.0

api/app/signals/apps/email_integrations/integrations/core.py, api/app/signals/apps/email_integrations/signal_receivers.py, api/app/signals/apps/email_integrations/tasks.py, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_split.txt, api/app/signals/apps/signals/managers.py, api/app/signals/apps/zds/signal_receivers.py, api/app/tests/apps/email_integrations/integrations/test_core.py, api/app/tests/apps/email_integrations/test_signal_receivers.py, api/app/tests/apps/email_integrations/test_tasks.py, api/app/tests/apps/signals/test_models.py
Still working on more tests for mail bodies --- but do not expect this part of the code to change much.
=> SIG-981 email on signal split

api/app/signals/__init__.py
=> Version bump 0.10.0

api/app/signals/apps/signals/managers.py, api/app/tests/apps/signals/test_managers.py
Fixed category key error + added tests
=> Fixed category key error + added tests

api/app/signals/apps/api/urls.py, api/app/signals/apps/api/v0/views.py, api/app/signals/apps/api/v1/public/views.py, api/app/signals/apps/api/v1/urls.py, api/app/signals/settings/base.py, api/app/signals/settings/development.py, api/app/tests/apps/api/test_api_v1_ml_predict_endpoint.py
SIG-1313: ML prediction through API with translations
=> feature/predict (SIG-1313)

api/app/signals/__init__.py
=> Version bump 0.14.0

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
document split and removed-from-category endpoints
=> Added endpoints to OpenAPI3 API description.

Jenkinsfile
Removed push image with acceptance tag to nexus
=> Removed push image with acceptance tag to nexus

api/app/signals/apps/email_integrations/core/messages.py
SIG-1828 [BE] Aanpassen servicebelofte "Grofvuil"
=> SIG-1828 [BE] Aanpassen servicebelofte "Grofvuil"

api/app/signals/apps/signals/migrations/0087_SIG-1987_SIG-1830_wonen.py, api/app/tests/apps/api/v1/test_private_departments.py
SIG-1987 & SIG-1830 wonen afdeling + categorien
=> SIG-1987 & SIG-1830 wonen afdeling + categorien

api/app/signals/apps/api/templates/api/swagger/openapi.yaml, api/app/signals/apps/users/v1/serializers/user.py
PUT and PATCH on user detail not documented, because these method implementations need a tweak.
=> SIG-2190 update swagger with respect to users endpoints

api/requirements.txt, import/requirements.txt
=> Django version bump to 2.2.10

api/requirements.txt, api/requirements/req-base.txt
Pinned elasticsearch requirement packages to the correct versions
=> Pinned elasticsearch requirement packages to the correct versions

api/app/signals/apps/signals/migrations/0096_categorie_changes.py, api/app/tests/apps/api/v1/test_private_category_endpoint.py
SIG-2242, SIG-2231, SIG-2169 & SIG-2232
=> SIG-2242, SIG-2231, SIG-2169 & SIG-2232

api/app/signals/apps/signals/managers.py, api/app/tests/apps/api/v1/test_private_signal_endpoint.py, api/app/tests/apps/signals/test_managers.py, api/app/tests/apps/signals/test_models.py, api/app/tests/apps/signals/test_workflow.py
SIG-2154 Added select_for_update + fixed unit tests
=> SIG-2154 Added select_for_update + fixed unit tests

api/app/signals/apps/api/templates/api/swagger/openapi.yaml, api/app/signals/apps/api/v1/filters.py, api/app/tests/apps/api/v1/test_filters.py
Changed filter param contact_details_present to contact_details
=> Changed filter param contact_details_present to contact_details

api/app/signals/apps/api/v1/serializers/nested/reporter.py, api/app/signals/apps/signals/managers.py, api/app/signals/apps/signals/migrations/0096_refactor_anonymize_reporter.py, api/app/signals/apps/signals/models/reporter.py, api/app/signals/apps/signals/tasks.py, api/app/tests/apps/api/v1/test_private_signal_endpoint.py, api/app/tests/apps/signals/factories.py, api/app/tests/apps/signals/test_task_anonymize_reporters.py
SIG-1976 refactor of anonymizing reporter data
=> SIG-1976 refactor of anonymizing reporter data

api/app/signals/apps/signals/migrations/0101_default_type_and_history_view.py, api/app/signals/apps/signals/models/history.py, api/app/signals/apps/signals/models/type.py, api/app/tests/apps/api/v1/test_history_endpoint.py, api/app/tests/apps/api/v1/test_private_departments.py, api/app/tests/apps/api/v1/test_private_signal_endpoint.py
Updated the history view + added default type to all signals
=> Updated the history view + added default type to all signals

api/Dockerfile, api/app/tests/apps/api/v1/test_private_departments.py, api/app/tox.ini, api/deploy/test/docker-compose.yml, api/deploy/test/run_tests.sh
Fixed security issue in Dockerfile + fixed randomly failing test in private department unit tests
=> Fixed security issue in Dockerfile

api/app/signals/apps/email_integrations/core/messages.py, api/app/signals/apps/signals/migrations/0102_auto_20200323_1513.py, api/app/signals/apps/signals/models/category.py, api/app/tests/apps/signals/factories.py
* SIG-2399 [BE] Category model aanpassen zodat de service belofte kan worden opgeslagen
* SIG-2402 [BE] Database migratie om huidige service belofte uit het bestand bij de juiste categorie in de database te plaatsen
=> SIG-2399 and SIG-2402 Category handling_message

api/requirements.txt, import/requirements.txt
Updated:
* Django==2.2.12
* Pillow==7.1.0
=> Updated Django and Pillow

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
Swagger documentation of the geography endpoint
=> Swagger documentation of the geography endpoint

api/app/signals/apps/signals/migrations/0104_auto_20200410_1001.py, api/app/signals/apps/signals/models/category.py, api/app/signals/apps/signals/models/department.py, api/app/signals/apps/signals/models/signal.py, api/app/signals/apps/signals/models/status.py, api/app/signals/apps/signals/models/status_message_template.py
SIG-2192 [BE] Namen rechten aangepast
=> SIG-2192 [BE] Namen rechten aangepast

api/app/signals/apps/signals/migrations/0107_category_changes_sig-2627.py, api/app/tests/apps/api/v1/test_private_category_endpoint.py
SIG-2627 Added new categorie "Ratten – in en rond een woning"
=> SIG-2627 Added new categorie "Ratten – in en rond een woning"

api/app/signals/apps/api/templates/api/pdf/print_signal.html, api/app/signals/apps/api/templates/api/swagger/openapi.yaml, api/app/signals/apps/api/v1/serializers/nested/reporter.py, api/app/signals/apps/signals/managers.py, api/app/signals/apps/signals/migrations/0112_reporter_sharing_allowed.py, api/app/signals/apps/signals/models/reporter.py, api/app/tests/apps/api/v1/json_schema/get_signals_v1_private_signals.json, api/app/tests/apps/api/v1/json_schema/get_signals_v1_private_signals_{pk}.json, api/app/tests/apps/api/v1/request_data/create_initial.json, api/app/tests/apps/api/v1/request_data/create_initial_public.json, api/app/tests/apps/api/v1/test_private_signal_endpoint.py
SIG-2773 Verklaring contactgegevens delen
=> SIG-2773 Verklaring contactgegevens delen

.gitignore, README.md, dex.dev.yml, dex/howto.txt, docker-compose.yml
- Save persistent data of Dex in volume
- Tailor Dex configuration to Signals
- Document the use of Dex
=> Improve Dex setup and documentation

api/app/signals/apps/dataset/management/commands/list_areas.py, api/app/signals/apps/dataset/management/commands/load_areas.py, api/app/signals/apps/dataset/sources/__init__.py, api/app/signals/apps/dataset/sources/cbs.py, api/app/signals/apps/dataset/sources/gebieden.py, api/app/signals/apps/dataset/sources/sia_stadsdeel.py, api/app/tests/apps/dataset/management/commands/test_load_areas.py, api/app/tests/apps/dataset/sources/sia_stadsdeel/test_load_sia_stadsdeel.py, api/app/tox.ini
First part of CBS data loading: municipal boundaries.
=> Download "CBS wijk- en buurtkaart" load municipal geometries

api/app/signals/apps/graphql/README.md, api/app/signals/apps/graphql/__init__.py, api/app/signals/apps/graphql/config.py, api/app/signals/apps/graphql/filters.py, api/app/signals/apps/graphql/middleware.py, api/app/signals/apps/graphql/query.py, api/app/signals/apps/graphql/schema.py, api/app/signals/apps/graphql/types.py, api/app/signals/apps/graphql/views.py, api/app/signals/settings/base.py, api/app/signals/urls.py, api/app/tests/apps/graphql/schema/schema.json, api/app/tests/apps/graphql/test_categories.py, api/app/tests/apps/graphql/test_departments.py, api/app/tox.ini, api/requirements.txt, api/requirements/req-base.txt
GraphQL setup
Categories and Departments list endpoints with pagination
Category and Department detail endpoints
=> GraphQL setup + implementation of Categories and Departments

api/app/signals/apps/reporting/csv/datawarehouse.py, api/app/tests/apps/reporting/test_datawarehouse.py
SIG-2823 CSV uitbreiden met velden voor Tableau
=> SIG-2823 CSV uitbreiden met velden voor Tableau

api/app/signals/apps/signals/migrations/0114_category_changes_SIG-2872.py, api/app/tests/apps/api/v1/test_private_category_endpoint.py
SIG-2872 Added subcategorie for Eikenprocessierups
=> SIG-2872 Added subcategorie for Eikenprocessierups

Jenkinsfile
There were some problems during deployment. The CMDB migration will be planned some other time.
=> Revert Jenkinsfile changes for CMDB

api/app/tests/apps/api/v1/test_private_signal_endpoint_create.py
Test that reproduces skipped signal ids.
=> Test that reproduces skipped signal ids.

api/app/signals/apps/api/generics/routers.py, api/app/signals/apps/api/templates/rest_framework/api.html, api/app/signals/apps/api/urls.py, api/app/signals/settings/base.py, api/app/signals/urls.py, api/app/tests/apps/api/v0/test_endpoints.py, api/app/tests/apps/api/v0/test_filters.py, api/app/tests/apps/api/v1/test_serializers.py, api/app/tests/apps/users/test_views.py
SIG-2341 & SIG-2342 Disabled V0 routing. Fixed tests so that V0 is still tested and the coverage is above the 90% mark
=> SIG-2341 & SIG-2342 Disabled V0

api/app/signals/apps/dataset/sources/cbs.py
=> Fix broken link in CBS 2019 import

api/app/signals/apps/email_integrations/reporter/mail_actions.py, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_afgehandeld.html, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_heropend.html, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_ingepland.html, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_optional.html, api/app/signals/apps/email_integrations/templates/email/signal_status_changed_optional.txt, api/app/tests/apps/email_integrations/reporter/test_mail.py
Email text adjustments/formatting
=> Email text adjustments/formatting

api/app/signals/apps/signals/models/history.py
=> SIG-3345 Textual change

api/app/signals/apps/api/v1/fields/extra_properties.py
Fix in SignalExtraPropertiesField when checking the category urls
=> Fix in SignalExtraPropertiesField when checking the category urls

.github/workflows/ci.yml
update repo before installing packages
=> Do apt update before installing packages

api/app/signals/apps/signals/migrations/0129_new_subcategory_kerstbomen.py, api/app/tests/apps/api/v1/test_private_category_endpoint.py
Added new subcatergory for "Kerstbomen"
=> Added new subcatergory for "Kerstbomen"

api/app/signals/auth/config.py, api/app/signals/auth/tokens.py, api/app/signals/settings/base.py, api/app/signals/settings/development.py, api/app/signals/settings/production.py, api/app/signals/settings/testing.py, api/app/tests/apps/users/test_backend.py, api/app/tests/auth/test_backend.py
Possible approach to supporting both authz and keycloak (and dex)
=> Add support for both authz and KeyCloak simultaneously (for migration).

api/app/tests/apps/api/v1/test_history_endpoint.py
Fixed sometimes failing test in TestHistoryAction
=> Fixed sometimes failing test in TestHistoryAction

docs/topics/signalen-and-standard-for-public-code.md
=> Update progress of implementing The Standard for Public Code

api/app/signals/apps/dsl/ExpressionEvaluator.py, api/app/signals/apps/dsl/evaluators/logical_evaluator.py, api/app/tests/apps/dsl/test_dsl.py
fixed issue with grammar that could not parse:
testint == 0 or testint == 1 or testint == 2
=> fix grammar, we should allow more than 2 and/or combination

.github/pull_request_template.md
Added a first pull_request_template.md, this is just a start and can change in the future
=> Added a pull_request_template.md

docs/CONTRIBUTING.md
Co-authored-by: Felix Faassen <felix@publiccode.net>
Co-authored-by: Jan Ainali <ainali.jan@gmail.com>
Mention mailing list, product owners for dev teams, and guidance
for feature requests.
Not Applicable: Only docs update
=> CONTRIBUTING.md reference product steering group

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
Fixed some reference errors in the SIA/Signalen Swagger file
=> SIG-3478 fix Swagger file structure errors

api/app/signals/apps/api/templates/api/swagger/openapi.yaml, api/app/signals/apps/api/v1/filters/signal.py, api/app/tests/apps/api/v1/test_filters.py
=> SIG-3400 allow filtering signals by reporter_email

docs/topics/signalen-and-standard-for-public-code.md
Update the checklist to align with the 0.2.0 wording of the [Standard for Public Code](https://standard.publiccode.net/) and [template](https://about.publiccode.net/activities/codebase-auditing/review-template.html).
(Not applicable)
=> Update standard checklist

api/app/signals/apps/api/v1/urls.py, api/app/signals/apps/api/v1/views/__init__.py, api/app/signals/apps/api/v1/views/signal.py, api/app/signals/settings/base.py, api/app/tests/apps/api/v1/test_public_map_signals_endpoint.py
- via django and drf -> 4secs
- via pg json func -> 30 ms (!)
Tipped by @tcoenen  for using json_build_object. Also did profiling, and could not see easy gains via DRF/django orm.
Any objections for doing it this way?
=> Configurable signal list endpoint for public map

docs/postman/Signals.postman_collection.json
Removed left over invalid bearer token from the postman collection
=> Removed left over invalid bearer token from the postman collection

api/app/signals/apps/email_integrations/admin.py
Disabled _validate_template_rendering function, TODO fix correctly
=> Disabled _validate_template_rendering function, TODO fix correctly

docs/topics/signalen-and-standard-for-public-code.md
Requirements have been updated thanks to the following:
* backend/issues#44 has been merged.
* Contributing file has been updated.
* Ongoing work on security.md.
* Add comment on review time.
* No CLA required (new in v.0.2.0).
* Ongoing work on SPDX headers.
Fixes #720
=> Update Standard checklist to current state

api/app/signals/apps/api/v1/filters/signal.py, api/app/tests/apps/api/v1/test_filters.py
We should allow filtering on assigned routing departments
=> allow filtering on routing department using department code

api/app/tests/apps/users/v1/test_filters.py
=> Remove unneeded TODO

api/app/signals/apps/health/urls.py, api/app/signals/apps/health/views.py, api/app/signals/settings/base.py, api/app/tests/apps/health/test_endpoints.py
=> Cleanup health app

api/app/signals/apps/api/v1/fields/attachment.py, api/app/signals/apps/api/v1/fields/signal.py, api/app/signals/apps/api/v1/serializers/signal.py, api/app/signals/apps/api/v1/urls.py, api/app/signals/apps/api/v1/views/_base.py, api/app/signals/apps/api/v1/views/signal.py, api/app/signals/apps/reporting/csv/datawarehouse/signals.py, api/app/signals/apps/reporting/csv/horeca.py, api/app/signals/apps/search/documents/signal.py, api/app/signals/apps/signals/factories/signal.py, api/app/signals/apps/signals/migrations/0136_auto_20210303_1451.py, api/app/signals/apps/signals/migrations/0137_auto_20210303_1451.py, api/app/signals/apps/signals/models/signal.py, api/app/signals/apps/signals/tasks.py, api/app/tests/apps/api/v1/test_private_signal_endpoint.py, api/app/tests/apps/api/v1/test_public_signal_endpoint.py, api/app/tests/apps/reporting/test_datawarehouse.py, api/app/tests/apps/signals/test_models.py
Cleanup + small refactor on the Signal model
=> Cleanup + small refactor on the Signal model

api/app/signals/apps/api/v1/filters/utils.py, api/app/tests/apps/api/v1/test_filters.py
Source lookup list uses wrong property.
fixes bug https://github.com/Signalen/backend/issues/121
=> use correct table/field for source lookup

check_spdx.py
=> SPDX header checker II

api/app/signals/apps/signals/management/commands/calculate_deadlines.py
Small addition to SIG-3642 / PR 761 to deal with data problems in SIA Amsterdam acceptance.
=> SIG-3642 special case missing category for old data

docs/topics/signalen-and-standard-for-public-code.md
Issue https://github.com/Signalen/backend/issues/69 can be closed.
The Signalen backend now meets this criterion.
=> Source files contain SPDX

api/app/signals/apps/email_integrations/utils.py, api/app/tests/apps/email_integrations/test_utils.py
=> Made the scheme optional

docs/CONTRIBUTING.md
https://github.com/Signalen/backend/issues/65
Include list of open standards which contributors may wish to be familiar with.
=> Issue #65, list open standards in use

api/app/signals/apps/signals/models/attachment.py, api/app/signals/settings/base.py, api/app/signals/settings/development.py, api/requirements.txt, api/requirements/req-base.txt
=> Remove unused imagekit dependency

api/app/signals/apps/api/views/signal_context.py
Fixed sorting on reporter context
=> Fixed sorting on reporter context

api/app/signals/apps/api/serializers/signal_context.py, api/app/signals/apps/api/templates/api/swagger/openapi.yaml
Added has_children to the reporter context response
=> Added has_children to the reporter context response

api/app/signals/settings/base.py, api/requirements.txt, api/requirements/req-base.txt, docs/topics/dependencies.md
=> Removed pygelf

docs/topics/application-design.md
Maarten Sukel's post gives a good overview of the classifier.
=> link blog post by Maarten Sukel about ML classification

utils/get_signals.py
Updated the log-in example to the new Datapunt Amsterdam KeyCloak URLs.
=> Fixed Amsterdam log-in example.

api/requirements.txt
=> Update Django to 3.2.5

api/app/signals/__init__.py
Version bump to version 2.2.0.
=> Version bump to version 2.2.0

api/app/signals/apps/signals/workflow.py
SIG-3801 [BE] Aanpassen status display names
=> SIG-3801 [BE] Aanpassen status display names

api/app/signals/apps/api/serializers/nested/status.py, api/app/tests/apps/api/test_reaction_request_flow_trigger.py
=> SIG-3887 add email available check to REST API for reaction requests

api/Dockerfile, api/requirements.txt, scripts/initialize.sh
Draft PR for `amsterdam/python:3.9.0-slim-buster` not yet cleaned-up due to time constraints.
=> Chore/slim buster 3.9.6 uwsgi via gcc

api/app/signals/apps/api/templates/api/pdf/extra_properties.html
Fixed extra properties in PDF for containers and eikenprocessierups
=> Fixed extra properties in PDF for containers and eikenprocessierups

api/app/signals/apps/questionnaires/templates/questionnaires/swagger/public_openapi.yaml
Fix copy paste error in Swagger.
=> fix path to session submit

api/app/signals/apps/questionnaires/tests/test_models.py
Extra tests for Session exipry
=> Session.is_expired tests

api/app/signals/apps/questionnaires/migrations/0004_make_session_duration_nullable.py, api/app/signals/apps/questionnaires/migrations/0005_make_session_duration_nullable.py, api/app/signals/apps/questionnaires/models/session.py, api/app/signals/apps/questionnaires/tests/test_models.py
Proposal: make duration nullable, the decision to enforce maximum duration for filling out a questionnaire to creator of questionnaire.
=> Chore make Session.duration nullable, update tests

api/app/signals/apps/questionnaires/admin/__init__.py, api/app/signals/apps/questionnaires/admin/admins.py, api/app/signals/apps/questionnaires/admin/inlines.py, api/app/signals/apps/questionnaires/models/questionnaire.py, api/app/signals/apps/questionnaires/models/session.py, api/app/signals/apps/signals/models/signal.py
SIG-3992 Questionnaires admin tweaks
=> SIG-3992 Questionnaires admin tweaks

api/app/signals/apps/questionnaires/tests/rest_framework/views/test_reaction_request_flow.py
Extra tests for reaction request flow. Test behavior of REST API when accessing sessions.
=> Add tests for REST API behavior when retrieving a session

api/app/signals/apps/api/app_settings.py, api/app/signals/settings/base.py, api/app/tests/apps/signals/test_map_generator.py
See: https://github.com/Amsterdam/signals-frontend/pull/1832
=> Update PDOK endpoint references

README.md, api/app/signals/__init__.py
=> Bump version number

docs/topics/signalen-and-standard-for-public-code.md
Fixes #903
Co-authored-by: Jan Ainali <jan@publiccode.net>
Update to match the Standard for Public Code v0.2.2 assessment template
=> Update Standard for Public Code assessment

api/requirements.txt
=> Bumped Django to 3.2.12

api/app/signals/__init__.py
Bumped the API version to 2.3.5
=> Bumped the API version to 2.3.5

api/app/signals/apps/api/json_schema/extra_properties_streetlights.json, api/app/signals/apps/api/serializers/signal.py, api/app/signals/apps/api/tests/test_private_signal_endpoint_create.py, api/app/signals/apps/api/tests/test_public_signal_endpoint.py
SIG4382 Additional check on the extra properties for lighting
=> SIG4382 Additional check on the extra properties for lighting

api/app/signals/settings/base.py
Added Ouder Amstel to the PDOK municipalities
=> Added Ouder Amstel to the PDOK municipalities

api/app/signals/apps/api/tests/test_private_category_endpoint.py, api/app/signals/apps/signals/migrations/0151_new_subcategories.py
SIG-4393 Added new sub categories for "container bijplaatsing", "rolcontainer is kapot" and "rolcontainer is vol" in the main category "afval"
=> Added 3 new subcategories to the main category "Afval"

api/app/signals/__init__.py
Bumped the version from 2.3.6 to 2.3.7
=> Bumped the version from 2.3.6 to 2.3.7

api/app/signals/apps/api/serializers/email_preview.py, api/app/signals/apps/api/templates/api/swagger/openapi.yaml, api/app/signals/apps/api/tests/test_private_signal_email_preview_endpoint.py, api/app/signals/apps/api/views/signal.py, api/app/signals/apps/email_integrations/actions/abstract.py, api/app/signals/apps/email_integrations/actions/signal_created.py, api/app/signals/apps/email_integrations/actions/signal_handeld.py, api/app/signals/apps/email_integrations/actions/signal_optional.py, api/app/signals/apps/email_integrations/actions/signal_reaction_request.py, api/app/signals/apps/email_integrations/actions/signal_reaction_request_received.py, api/app/signals/apps/email_integrations/rules/abstract.py, api/app/signals/apps/email_integrations/rules/signal_created.py, api/app/signals/apps/email_integrations/rules/signal_handeld.py, api/app/signals/apps/email_integrations/rules/signal_optional.py, api/app/signals/apps/email_integrations/rules/signal_reaction_request.py, api/app/signals/apps/email_integrations/rules/signal_reaction_request_received.py, api/app/signals/apps/email_integrations/rules/signal_reopened.py, api/app/signals/apps/email_integrations/rules/signal_scheduled.py, api/app/signals/apps/email_integrations/services.py, api/app/signals/apps/email_integrations/tests/test_actions.py, api/app/signals/apps/email_integrations/tests/test_rules.py, api/app/signals/apps/email_integrations/tests/test_services.py, api/app/signals/apps/email_integrations/utils.py, docs/adr/0002-email_preview.md
WIP First setup of the email preview endpoint
=> Email preview

api/app/signals/__init__.py
Bumped the version from 2.3.7 to 2.4.0
=> Bumped the version from 2.3.7 to 2.4.0

api/app/signals/apps/api/views/signals/public/signals.py
Added ordering on created_at to the public signals geography endpoint, default ordering is -create_at
=> Added ordering on created_at to the public signals geography endpoint

api/app/signals/__init__.py
=> Version bump to 2.4.1

.github/workflows/build_and_push_docker_image.yml
Also create a new "latest" image and push to docker when creating a new release
=> Also create a new "latest" image and push to docker when creating a new release

api/app/signals/settings/base.py, api/app/signals/settings/testing.py, api/requirements.txt
Made the CORS settings configurable
=> Made the CORS settings configurable

api/app/signals/__init__.py
Release branch for version 2.4.2
=> Version bump to version 2.4.2

api/app/signals/apps/email_integrations/actions/signal_created.py, api/app/signals/apps/email_integrations/tests/test_actions.py
The e-mail address and phone number of the reporter are obscured and added to the e-mail template context.
This is only used for the email that is sent to the reporter confirming the creation of a Signal.
Locally tested the functionality, see screenshot for result (this is configuration that is not part of this PR):
=> Added obscured email address and phone number of the reporter to the email context for the created email template

api/app/signals/__init__.py
=> Bumped API version to 2.4.4

api/app/signals/settings/base.py
Added http://meldingen.weesp.nl and https://meldingen.weesp.nl to the DEFAULT_CORS_ALLOWED_ORIGINS
=> Addded http://meldingen.weesp.nl and https://meldingen.weesp.nl to the DEFAULT_CORS_ALLOWED_ORIGINS

api/app/signals/settings/base.py, api/app/signals/settings/testing.py
Moved the configuration for the CORS_ALLOWED_ORIGINS to the OpenStack project for Amsterdam
=> Moved the configuration for the CORS_ALLOWED_ORIGINS to the OpenStack project for Amsterdam

api/app/signals/apps/signals/migrations/0156_alter_attachment_options.py, api/app/signals/apps/signals/models/attachment.py, api/app/signals/apps/users/tests/v1/test_permissions.py, api/app/signals/apps/users/v1/views/permission.py, api/app/signals/settings/base.py
=> Translate attachment delete permission names to Dutch

api/app/signals/apps/api/tests/test_private_category_endpoint.py, api/app/signals/apps/signals/migrations/0157_new_subcategories.py
New subcategories for:
- Loslopende agressieve honden
- Wonen ondermijning
=> Added 2 new sub categories

scripts/initialize.sh
Increase UWSGI buffer size to match Signalen production deployments.
=> Increase UWSGI buffer size to match Signalen production deployments.

api/app/signals/apps/email_integrations/signal_receivers.py
Fixed the update_status_handler
=> Fixed the update_status_handler

api/app/signals/apps/email_integrations/models.py
remove duplicate key and add extra value text
=> remove duplicate key choice and add extra value text

api/app/signals/__init__.py
Bumped the API version to 2.5.0
=> Bumped the API version to 2.5.0

api/app/signals/apps/api/serializers/signal.py
Added id_display to the PublicSignalSerializerDetail
=> Added id_display to the PublicSignalSerializerDetail

api/app/signals/apps/feedback/serializers.py, api/app/signals/apps/feedback/tests/test_feedback.py
Added signal_id to the response of the feedback form
=> Added signal_id to the response of the feedback form

.github/workflows/manual_build_and_push_docker_image.yml
A github action to manually build a Docker image for a given tag and push it to docker hub
=> A github action to manually build a Docker image (and push it to the docker hub) for the given tag

api/app/signals/__init__.py
=> Bumped API version to 2.7.1

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
=> Swagger fix

api/app/signals/apps/sigmax/stuf_protocol/outgoing/creeerZaak_Lk01.py, api/app/signals/apps/sigmax/tests/stuf_protocol/outgoing/test_creeerZaak_Lk01.py
Added Priority.PRIORITY_LOW to the description send to Sigmax
=> Added Priority.PRIORITY_LOW to the description send to Sigmax

api/app/signals/apps/questionnaires/templates/questionnaires/swagger/public_openapi.yaml
Added the correct answer payloads to the swagger file
=> Added the correct answer payloads to the swagger file

api/app/signals/apps/signals/admin/category.py
Added CSV download of categories and status message templates to the Django Admin
=> Django Admin CSV download for categories and status message templates

api/app/signals/apps/users/admin.py
Added the departments to the Django Admin user list view and the CSV download
=> Add departments to the Django admin user list view and in CSV download

api/app/signals/apps/api/templates/api/swagger/openapi.yaml
Added the v1/public/feedback/standard_answers/ to the swagger file
=> Added the v1/public/feedback/standard_answers/ to the swagger file

api/app/signals/apps/api/urls.py, api/app/signals/apps/search/rest_framework/__init__.py, api/app/signals/apps/search/rest_framework/pagination.py, api/app/signals/apps/search/rest_framework/views.py, api/app/signals/apps/search/urls.py
Refactored the Search app to contain all rest code in the "rest_framework" folder
=> Refactored the Search app to contain all rest code in the "rest_framework" folder

api/app/signals/apps/reporting/csv/utils.py, api/app/signals/apps/reporting/management/commands/dump_tdo_csv_files.py, api/app/signals/apps/reporting/management/commands/dump_test_csv.py, api/app/signals/apps/reporting/management/commands/dumpcsv.py, api/app/signals/apps/reporting/models/export.py, api/app/signals/apps/reporting/tests/csv/test_datawarehouse.py, api/app/signals/apps/reporting/utils.py, api/app/signals/settings/base.py, api/requirements.txt, docker-compose.yml
Added AzureStorage as a configurable storage. It is now possible to use AzureStorage, SwiftStorage or the FileSystemStorage.
To configure the AzureStorage set the following env variables:
- AZURE_STORAGE_ENABLED (Default is False)
- AZURE_STORAGE_ACCOUNT_NAME
- AZURE_STORAGE_ACCOUNT_KEY
- AZURE_STORAGE_URL_EXPIRATION_SECS (Seconds before a URL expires, set to None to never expire it. Be aware the container must have public read permissions in order to access a URL without expiration date. Default is None)
- AZURE_STORAGE_CONTAINER_NAME (Default is '')
- DWH_AZURE_STORAGE_CONTAINER_NAME (Default is AZURE_STORAGE_CONTAINER_NAME)
It is not possible to configure the AzureStorage and the SwiftStorage. Only one can be used.
=> Added AzureStorage as a configurable storage. It is now possible to use

api/app/signals/__init__.py
Bumped release version to 2.8.1
=> Release 2.8.1

api/app/signals/apps/questionnaires/rest_framework/views/public/questionnaires.py, api/app/signals/apps/questionnaires/rest_framework/views/public/questions.py, api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_questionnaires_endpoint.py, api/app/signals/apps/questionnaires/tests/rest_framework/views/public/test_public_questions_endpoint.py
Questionnaire and Questions should not be exposed in list endpoints.
=> Disable questionnaires and questions list endpoints in public API

api/app/signals/__init__.py
Bumped the version from 2.8.1 to 2.8.2
=> Bumped the version from 2.8.1 to 2.8.2

api/app/signals/apps/dataset/management/commands/load_cbs_for_municipality.py, api/app/signals/apps/dataset/sources/cbs.py, docker-compose/scripts/initialize.sh
The current import script is broken as CBS removed the 2021 v1 dataset. This updates the dataset to 2022 v1.
=> Update CBS wijk- en buurtkaart import to 2022 v1

api/app/signals/__init__.py
Bumped the release version to 2.9.0
=> Bumped the release version to 2.9.0

api/app/signals/apps/api/templates/api/swagger/openapi.yaml, docs/README.md, docs/topics/api/table_of_contents.md, docs/topics/api/v1/private/01.connecting_to_the_api.md, docs/topics/api/v1/private/signals/01.creating_a_signal.md, docs/topics/api/v1/private/signals/02.updating_a_signal.md, docs/topics/api/v1/private/signals/03.listing_signals.md, docs/topics/api/v1/private/signals/04.signal_detail.md, docs/topics/authorization.md
Technical private Signals API documentation. This PR adds step one of many to improve the documentation of the API.
=> Technical private Signals API documentation

api/app/signals/apps/my_signals/rest_framework/serializers/nested/status.py
On the "My Signals" detail page the status translation should be the same as in the history. Added the translations.
=> "My Signals" Detail page added status translations

api/app/signals/__init__.py
=> Bumped version to 2.10.0

api/app/signals/__init__.py
Bumped the API version to 2.11.0
=> Release 2.11.0

api/app/signals/apps/signals/migrations/0166_rename_status_forward_to_external.py, api/app/signals/apps/signals/workflow.py
Naming for the DOORGEZET_NAAR_EXTERN state was still "Doorzetten naar extern", this PR fixes it to be "Doorgezet naar extern".
=> Fix naming for DOORGEZET_NAAR_EXTERN state.

api/app/signals/settings/base.py
This adds the ability to configure the SECURE_SSL_REDIRECT setting through an environment variable
=> Add ability to configure SECURE_SSL_REDIRECT setting

api/app/signals/apps/email_integrations/templates/admin/change_email_template_form.html
Added the new email template variables to the admin template
=> Added the new email template variables to the admin template

Dockerfile, docker-compose.yml, docker-compose/scripts/initialize.sh
Restore the "old" directory structure inside the container as currently the helm chart needs that.
=> Restore directory structure within container image

app/signals/admin/__init__.py, app/signals/admin/oidc/__init__.py, app/signals/admin/oidc/tests/__init__.py
Added missing __init__.py files to the app/signals/admin folders
=> Added missing __init__.py files to the app/signals/admin folders

app/signals/apps/api/generics/exceptions.py
Removed the PreconditionFailed and NotImplementedException generic exceptions as they are not used
=> Removed the unused PreconditionFailed and NotImplementedException exceptions

app/signals/auth/tokens.py
Fixed CodeQL issues found in auth/tokens.py "Information exposure through an exception"
=> Fixed CodeQL issues found in auth/tokens.py

app/signals/apps/api/generics/pagination.py, app/signals/apps/search/rest_framework/pagination.py
Fixed CodeQL issues found in generic and search pagination classes "Information exposure through an exception"
=> Fixed CodeQL issues found in generic and search pagination classes

.github/workflows/build_and_push_to_docker_hub.yml, .github/workflows/ci.yml, .github/workflows/manual_build_and_push_to_docker_hub.yml
=> Update github actions

app/signals/apps/questionnaires/services/reaction_request.py
Renamed the short_label from "Reactie melder" to "Onze vraag aan u"
=> Renamed the short_label from "Reactie melder" to "Onze vraag aan u"

app/requirements.txt, docker-compose.yml
Upgrade to elasticsearch 7.
Depends on https://github.com/Amsterdam/signals/pull/1204
=> Chore/upgrade elasticsearch to version 7.x

app/requirements.txt, app/requirements/req-base.txt, app/signals/settings/base.py, docker-compose/scripts/initialize.sh
This PR adds OpenCensus tracing to the Django application.
=> Add OpenCensus tracing

app/signals/apps/api/templates/api/swagger/openapi.yaml
Update the OpenApi spec to reflect the new category "configuration" field.
=> Update the openapi spec

app/signals/apps/sigmax/stuf_protocol/outgoing/stuf.py
A meaningful description explaining the change/fix that is provided in this PR
=> Set timeout for outgoing requests to sigmax

app/signals/apps/signals/tasks.py
We apply locking on the Signal for every update. Therefore writes can fail when two updates arrive at the same time (e.g. routing rules are finished and attachment arrives). This leads to errors like:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.LockNotAvailable: could not obtain lock on row in relation "signals_signal"
```
The PR retries applying the the routing rules for 5 times when a lock prevents the routing rules from updating the Signal. This reduces the chance that routing rules cannot be applied significantly.
Fixes [Teams issue](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt …
=> Retry applying routing rules for 5 times when LockNotAvailable

app/signals/apps/api/tests/test_status_message_endpoint.py, app/signals/apps/search/documents/status_message.py, app/signals/apps/search/management/commands/delete_status_messages_index.py, app/signals/apps/search/management/commands/index_status_messages.py, app/signals/apps/search/management/commands/init_status_messages_index.py, app/signals/apps/search/signal_receivers.py, app/signals/apps/search/tasks.py, app/signals/apps/search/transformers/__init__.py, app/signals/apps/search/transformers/status_message.py
Index status messages in elasticsearch
=> Index status messages in elasticsearch

.github/workflows/ci.yml, app/signals/apps/dataset/tests/sources/sia_stadsdeel/test_load_sia_stadsdeel.py
Run github ci action on ubuntu-latest and no need to install graphiz in the step "Install geospatial libraries"
=> Run github ci action on ubuntu-latest

app/signals/settings/base.py
Added setting AZURE_CUSTOM_DOMAIN
=> Added setting AZURE_CUSTOM_DOMAIN

app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt
=> Updated the requirements

app/signals/apps/api/templates/api/swagger/openapi.yaml, app/signals/apps/api/urls.py, app/signals/apps/search/documents/status_message.py, app/signals/apps/search/elasticsearch_dsl/__init__.py, app/signals/apps/search/elasticsearch_dsl/search.py, app/signals/apps/search/rest_framework/serializers.py, app/signals/apps/search/rest_framework/views.py
Faceted search for status messages.
=> Search endpoint status messages

.dockerignore, app/Makefile, dev-up.sh, docs/development/local.md, docs/development/managing_dependencies.md
Make the process of starting a dev environment, including all dev dependencies, a little easier.
=> Dependency management in container

docs/adr/0004-reporter_updates.md
Architecture decision record for the signal reporter information updates.
=> Add draft ADR for updating signal reporter information

app/signals/settings/base.py
This PR always adds the 'drf_spectacular' and 'drf_spectacular_sidecar' apps to the INSTALLED_APPS list in the base settings file.
=> Always add the 'drf_spectacular' and 'drf_spectacular_sidecar' apps to the INSTALLED_APPS

app/signals/apps/feedback/rest_framework/views.py
Add/Fix the OpenAPI specs generation for the v1 public feedback endpoints using drf-spectacular
=> Add/Fix the OpenAPI specs generation for the v1 public feedback endpoints using drf-spectacular

app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt
=> Updated requirements

app/signals/apps/email_integrations/email_verification/reporter_mailer.py, app/signals/apps/email_integrations/email_verification/reporter_verification.py, app/signals/apps/email_integrations/models.py, app/signals/apps/email_integrations/tests/email_verification/test_reporter_mailer.py, app/signals/apps/email_integrations/tests/email_verification/test_reporter_verfication.py, app/signals/apps/email_integrations/tests/test_email_templates.py
Add support for emailing the current reporter when a change of contact information has been requested.
=> Send mail to current reporter

Dockerfile, dev-up.sh, docker-compose.yml, docs/development/local.md
Use a build arg instead of the dev-up.sh script
=> Use a build arg instead of the dev-up.sh script

app/signals/apps/feedback/rest_framework/serializers.py
Added "open_answer" to the StandardAnswerSerializer
=> Added "open_answer" to the StandardAnswerSerializer

app/signals/apps/api/serializers/signal_reporter.py, app/signals/apps/api/tests/test_private_signal_reporters.py, app/signals/apps/api/views/signals/private/signal_reporters.py, app/signals/apps/signals/models/reporter.py, app/signals/apps/signals/tests/test_reporter_state_machine.py
Implement reporter verify email transition.
=> Implement reporter verify email transition

app/signals/apps/api/serializers/signal_reporter.py, app/signals/apps/api/tests/test_private_signal_endpoint.py, app/signals/apps/api/tests/test_public_signal_endpoint.py, app/signals/apps/api/views/email_verification.py, app/signals/apps/signals/managers.py, app/signals/apps/signals/models/reporter.py, app/signals/apps/signals/tests/test_reporter_state_machine.py
Implement reporter approve state transition.
=> Implement reporter approve state transition

app/signals/apps/api/tests/test_private_signal_reporters.py, app/signals/apps/signals/models/reporter.py, app/signals/apps/signals/tests/test_reporter_state_machine.py
When current reporter has an email address send notification email.
=> When current reporter has an email address send notification email

app/signals/apps/api/serializers/signal_reporter.py, app/signals/apps/api/tests/test_email_verification_endpoint.py, app/signals/apps/api/views/email_verification.py, app/signals/apps/history/models/log.py, app/signals/apps/signals/models/reporter.py
Handle history for reporter updates
=> Handle history for reporter updates

app/signals/apps/signals/models/reporter.py
Assign current reporter to signal.
=> Assign current reporter to signal

app/signals/apps/api/serializers/signal_reporter.py, app/signals/apps/api/tests/test_private_signal_reporters.py
Cancel previous reporter if not approved.
=> Cancel previous reporter if not approved

app/signals/apps/api/views/source.py
Add drf-spectacular schema extension to improve API documentation for private Sources endpoint
=> Add drf-spectacular schema extension to improve API documentation for private Sources endpoint

app/signals/apps/api/views/expression.py
Refactored PrivateExpressionViewSet and added drf-spectacular schema extension to improve API documentation
=> Refactored PrivateExpressionViewSet and added drf-spectacular schema extension to improve API documentation

app/signals/apps/signals/models/reporter.py
Added ordering to the Reporter model
=> Added ordering to the Reporter model

docs/adr/0004-reporter_updates.md
=> Update reporter updates ADR

docs/adr/0006-data-retention-and-deletion-delete-signals-in-state-y-after-x-days.md
Added ADR 0006 Data retention and deletion - Delete signals in state Y after X days
=> Added ADR 0006 Data retention and deletion - Delete signals in state Y after X days

app/signals/apps/signals/migrations/0195_auto_20230821_1059.py
Update all attachments uploaded by reporters with a single statement
=> Update all attachments uploaded by reporters with a single statement

.github/workflows/build_and_push_to_docker_hub.yml, .github/workflows/build_and_push_to_github_container_registry.yml, .github/workflows/manual_build_and_push_to_docker_hub.yml, Dockerfile, docker-compose.yml
Introduce dev stage instead of conditional section in main stage.
=> Introduce dev stage instead of conditional section in main stage

docker-compose/scripts/initialize.sh
Refactor entrypoint script for dev environment.
=> Refactor entrypoint script for dev environment

app/signals/apps/email_integrations/email_verification/reporter_mailer.py, app/signals/apps/email_integrations/tests/email_verification/test_reporter_mailer.py, app/signals/apps/email_integrations/tests/test_email_templates.py
Provide signal context to reporter mail templates.
=> Provide signal context to reporter mail templates

app/signals/apps/signals/admin/deleted_signals.py
Added `date_hierarchy` to the DeletedSignalAdmin + us the admin.action decorator
=> Added `date_hierarchy` to the DeletedSignalAdmin + us the admin.action decorator

app/signals/apps/search/rest_framework/views.py
Enable sorting search results by date.
=> Enable sorting search results by date

.github/workflows/ci.yml, docker-compose.test.yml
=> Use docker-compose in ci

app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt, app/signals/apps/api/tests/test_private_signal_endpoint.py
=> Upgrade dependencies

app/mypy-baseline.txt, app/signals/apps/reporting/csv/datawarehouse/tasks.py, app/signals/apps/reporting/csv/utils.py, app/signals/apps/reporting/rest_framework/serializers.py, app/signals/apps/reporting/rest_framework/views.py, app/signals/apps/reporting/tests/rest_framework/test_views.py
=> Solve mypy issues reporting

app/requirements/requirements.in, app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt
Removed unused `datapunt-authorization-django` package
=> Removed unused `datapunt-authorization-django` package

app/signals/apps/questionnaires/rest_framework/views/public/sessions.py
Fixed: Information exposure through an exception
=> Fixed: Information exposure through an exception

.github/workflows/ci.yml
Update github action checkout from v3 to v4 for the ci workflow
=> Update github action checkout from v3 to v4 for the ci workflow

.github/workflows/build_and_push_to_docker_hub.yml
Improve Docker image build and push workflow
- Update actions/checkout to v4
- Use the docker/login-action for logging into Docker Hub
- Docker meta extraction with docker/metadata-action v5
- Docker image build and push with docker/build-push-action v5
- Generate 'latest' tag for releases
=> Improve Docker image build and push workflow

app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt
=> Update project dependencies

app/signals/apps/api/middleware.py, app/signals/apps/api/tests/test_maintenance_mode.py
Exempt the health-check from the maintenance mode
=> Exempt the health-check from the maintenance mode

app/signals/apps/feedback/models.py
Updated help text on the StandardAnswer model
=> Updated help text on the StandardAnswer model

.dockerignore, .github/workflows/ci.yml, app/requirements/requirements.in, app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt, app/signals/apps/api/tests/test_private_signal_endpoint.py, app/signals/apps/history/migrations/0001_initial.py, app/signals/apps/history/models/log.py, app/signals/apps/history/tests/services/test_signal_log.py, app/signals/apps/signals/admin/area.py, app/signals/apps/signals/migrations/0044_auto_20190418_1143.py, app/signals/apps/signals/migrations/0059_auto_20190605_1109.py, app/signals/apps/signals/models/category.py, app/signals/apps/signals/models/signal.py, app/signals/apps/signals/models/status_message_template.py, app/signals/settings.py, app/tox.ini, docker-compose.test.yml, docker-compose.yml
This pull request aims to upgrade Django from version 3.2.x to the latest Long-Term Support (LTS) version, 4.2.x. The upgrade will be performed in a step-by-step manner, first transitioning through version 4.0.x and then 4.1.x before reaching the final target version.
Upgrading to the latest LTS version of Django is essential to ensure that the project remains secure, up-to-date, and leverages the latest features and improvements. The incremental upgrade process minimizes potential issues and allows us to identify and address compatibility challenges at each stage.
Django release notes for each version can be found on [Django 4.2 Release Notes](https://docs.djangoproject.com/en/4.2/releases/).
1. **Upgrade to Django 4.0.x:**
- Update project dependencies to include Django 4.0.x.
- Update …
=> Upgrading Django from 3.2.x to 4.2.x

app/signals/apps/feedback/models.py
Modify the help texts as requested in SIG-5774.
=> Modify help texts

app/signals/apps/feedback/models.py
Accidentally modified the help text for order instead of open answer. This PR corrects that.
=> Correct the help texts

app/requirements/requirements.txt, app/requirements/requirements_dev.txt, app/requirements/requirements_test.txt
=> chore: Update dependencies

app/signals/__init__.py
=> bump version

app/signals/settings.py
=> fix bug when checking if user is unauthenticated

app/signals/apps/sigmax/stuf_protocol/outgoing/creeerZaak_Lk01.py, app/signals/apps/sigmax/tests/stuf_protocol/outgoing/test_creeerZaak_Lk01.py, app/signals/apps/signals/factories/__init__.py, app/signals/apps/signals/factories/buurt.py
=> extend omschrijving with more data

.github/workflows/ci.yml
Upgrade to version 4 of upload-artifact action, as support for v3 is ending soon.
=> Upgrade upload-artifact action to v4

app/signals/apps/sigmax/stuf_protocol/outgoing/creeerZaak_Lk01.py, app/signals/apps/sigmax/tests/stuf_protocol/outgoing/test_creeerZaak_Lk01.py
=> prepend signalering to omschrijving

app/signals/apps/signals/management/commands/free_external_sent_signals.py, app/signals/apps/signals/tests/management/commands/test_free_external_sent_signals.py
=> adds command to fix Signals stuck in VERZONDEN
